In [1]:
import os
import glob
import pandas as pd

In [2]:
print(os.listdir("../../data/raw"))

['.ipynb_checkpoints', 'Alta10_MetMast_WindSpeed_10m_2026-01.parquet', 'Alta10_MetMast_WindSpeed_10m_2026-02.parquet', 'Alta10_MetMast_WindSpeed_10m_2026-03.parquet', 'Alta10_MetMast_WindSpeed_10m_2026-04.parquet', 'Alta10_MetMast_WindSpeed_10m_2026-05.parquet', 'Alta10_MetMast_WindSpeed_10m_2026-06.parquet', 'Alta10_MetMast_WindSpeed_10m_2026-07.parquet', 'Alta10_MetMast_WindSpeed_10m_2026-08.parquet', 'Alta10_MetMast_WindSpeed_10m_2026-09.parquet', 'Alta10_Turbine_Points_10m_2026-01.parquet', 'Alta10_Turbine_Points_10m_2026-02.parquet', 'Alta10_Turbine_Points_10m_2026-03.parquet', 'Alta10_Turbine_Points_10m_2026-04.parquet', 'Alta10_Turbine_Points_10m_2026-05.parquet', 'Alta10_Turbine_Points_10m_2026-06.parquet', 'Alta10_Turbine_Points_10m_2026-07.parquet', 'Alta10_Turbine_Points_10m_2026-08.parquet', 'Alta10_Turbine_Points_10m_2026-09.parquet']

In [6]:
parquet_files = glob.glob("../../data/raw/*.parquet")

print(parquet_files)
print("Number of files:", len(parquet_files))

df = pd.concat(
    [pd.read_parquet(file) for file in parquet_files],
    ignore_index=True
)

df.head()

['../../data/raw\\Alta10_MetMast_WindSpeed_10m_2026-01.parquet', '../../data/raw\\Alta10_MetMast_WindSpeed_10m_2026-02.parquet', '../../data/raw\\Alta10_MetMast_WindSpeed_10m_2026-03.parquet', '../../data/raw\\Alta10_MetMast_WindSpeed_10m_2026-04.parquet', '../../data/raw\\Alta10_MetMast_WindSpeed_10m_2026-05.parquet', '../../data/raw\\Alta10_MetMast_WindSpeed_10m_2026-06.parquet', '../../data/raw\\Alta10_MetMast_WindSpeed_10m_2026-07.parquet', '../../data/raw\\Alta10_MetMast_WindSpeed_10m_2026-08.parquet', '../../data/raw\\Alta10_MetMast_WindSpeed_10m_2026-09.parquet', '../../data/raw\\Alta10_Turbine_Points_10m_2026-01.parquet', '../../data/raw\\Alta10_Turbine_Points_10m_2026-02.parquet', '../../data/raw\\Alta10_Turbine_Points_10m_2026-03.parquet', '../../data/raw\\Alta10_Turbine_Points_10m_2026-04.parquet', '../../data/raw\\Alta10_Turbine_Points_10m_2026-05.parquet', '../../data/raw\\Alta10_Turbine_Points_10m_2026-06.parquet', '../../data/raw\\Alta10_Turbine_Points_10m_2026-07.parquet', '../../data/raw\\Alta10_Turbine_Points_10m_2026-08.parquet', '../../data/raw\\Alta10_Turbine_Points_10m_2026-09.parquet']
Number of files: 18

,utcTime,ALTA10-SCEWF-WTG150-AirDensity,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient-Merged,ALTA10-SCEWF-WTG150-KPI-RealPowerAC,ALTA10-SCEWF-WTG150-KPI-TheoreticalPower,ALTA10-SCEWF-WTG150-KPI-WindSpeed,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient,ALTA10-SCEWF-WTG150-RealPowerAC,ALTA10-SCEWF-WTG150-NacellePosition,ALTA10-SCEWF-WTG150-BladePosition2,...,ALTA10-SCEWF-WTG197-NacellePosition,ALTA10-SCEWF-WTG197-BladePosition1,ALTA10-SCEWF-WTG197-BladePosition2,ALTA10-SCEWF-WTG197-BladePosition3,ALTA10-SCEWF-WTG197-BladeSetpointPosition1,ALTA10-SCEWF-WTG197-BladeSetpointPosition2,ALTA10-SCEWF-WTG197-BladeSetpointPosition3,ALTA10-SCEWF-WTG197-WindSpeed,ALTA10-SCEWF-WTG197-WindDirection,ALTA10-SCEWF-WTG197-WindDirectionRelative
0,2026-01-01 08:00:00,1.092081,8.299405,672.60510,746.68463,6.906036,8.299405,670.286714,118.785714,-1.056245,...,62.500000,-0.15625,0.35788,-0.211483,-0.164664,0.369037,-0.207469,8.664497,54.739130,-6.454545
1,2026-01-01 08:10:00,0.800856,8.573889,541.30096,466.00030,6.609679,8.573889,542.747853,117.066667,-1.077751,...,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,8.000924,52.763514,-5.510949
2,2026-01-01 08:20:00,1.089478,8.972823,237.94884,292.86000,5.210308,8.972823,239.185173,118.812500,-0.445800,...,58.666667,NaN,NaN,NaN,NaN,NaN,NaN,8.207936,53.654930,-4.808824
3,2026-01-01 08:30:00,0.800936,8.531316,503.22354,443.03992,6.510418,8.531316,504.556470,NaN,-1.205972,...,67.333333,NaN,NaN,NaN,NaN,NaN,NaN,8.099642,60.771812,-6.313869
4,2026-01-01 08:40:00,1.090836,8.621079,444.42767,500.71185,6.093416,8.621079,444.157211,130.000000,-1.205672,...,67.100000,NaN,NaN,NaN,NaN,NaN,NaN,8.257563,60.806897,-6.318519

In [12]:
first_file = parquet_files[9]

df1 = pd.read_parquet(first_file)

df1.head()

,utcTime,ALTA10-SCEWF-WTG150-AirDensity,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient-Merged,ALTA10-SCEWF-WTG150-KPI-RealPowerAC,ALTA10-SCEWF-WTG150-KPI-TheoreticalPower,ALTA10-SCEWF-WTG150-KPI-WindSpeed,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient,ALTA10-SCEWF-WTG150-RealPowerAC,ALTA10-SCEWF-WTG150-NacellePosition,ALTA10-SCEWF-WTG150-BladePosition2,...,ALTA10-SCEWF-WTG197-NacellePosition,ALTA10-SCEWF-WTG197-BladePosition1,ALTA10-SCEWF-WTG197-BladePosition2,ALTA10-SCEWF-WTG197-BladePosition3,ALTA10-SCEWF-WTG197-BladeSetpointPosition1,ALTA10-SCEWF-WTG197-BladeSetpointPosition2,ALTA10-SCEWF-WTG197-BladeSetpointPosition3,ALTA10-SCEWF-WTG197-WindSpeed,ALTA10-SCEWF-WTG197-WindDirection,ALTA10-SCEWF-WTG197-WindDirectionRelative
DataTimeStamp,,,,,,,,,,,,,,,,,,,,,
2026-01-01 00:00:00,2026-01-01 08:00:00,1.092081,8.299405,672.60510,746.68463,6.906036,8.299405,670.286714,118.785714,-1.056245,...,62.500000,-0.15625,0.35788,-0.211483,-0.164664,0.369037,-0.207469,8.664497,54.739130,-6.454545
2026-01-01 00:10:00,2026-01-01 08:10:00,0.800856,8.573889,541.30096,466.00030,6.609679,8.573889,542.747853,117.066667,-1.077751,...,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,8.000924,52.763514,-5.510949
2026-01-01 00:20:00,2026-01-01 08:20:00,1.089478,8.972823,237.94884,292.86000,5.210308,8.972823,239.185173,118.812500,-0.445800,...,58.666667,NaN,NaN,NaN,NaN,NaN,NaN,8.207936,53.654930,-4.808824
2026-01-01 00:30:00,2026-01-01 08:30:00,0.800936,8.531316,503.22354,443.03992,6.510418,8.531316,504.556470,NaN,-1.205972,...,67.333333,NaN,NaN,NaN,NaN,NaN,NaN,8.099642,60.771812,-6.313869
2026-01-01 00:40:00,2026-01-01 08:40:00,1.090836,8.621079,444.42767,500.71185,6.093416,8.621079,444.157211,130.000000,-1.205672,...,67.100000,NaN,NaN,NaN,NaN,NaN,NaN,8.257563,60.806897,-6.318519

In [11]:
print("File:", first_file)
print("Shape:", df1.shape)
print("Columns:", df1.columns.tolist())

File: ../../data/raw\Alta10_MetMast_WindSpeed_10m_2026-01.parquet
Shape: (0, 0)
Columns: []

In [13]:
import os

for file in parquet_files:
    print(os.path.basename(file), os.path.getsize(file))

Alta10_MetMast_WindSpeed_10m_2026-01.parquet 976
Alta10_MetMast_WindSpeed_10m_2026-02.parquet 976
Alta10_MetMast_WindSpeed_10m_2026-03.parquet 976
Alta10_MetMast_WindSpeed_10m_2026-04.parquet 976
Alta10_MetMast_WindSpeed_10m_2026-05.parquet 976
Alta10_MetMast_WindSpeed_10m_2026-06.parquet 976
Alta10_MetMast_WindSpeed_10m_2026-07.parquet 976
Alta10_MetMast_WindSpeed_10m_2026-08.parquet 976
Alta10_MetMast_WindSpeed_10m_2026-09.parquet 976
Alta10_Turbine_Points_10m_2026-01.parquet 23554486
Alta10_Turbine_Points_10m_2026-02.parquet 21304942
Alta10_Turbine_Points_10m_2026-03.parquet 26976189
Alta10_Turbine_Points_10m_2026-04.parquet 27624274
Alta10_Turbine_Points_10m_2026-05.parquet 27997883
Alta10_Turbine_Points_10m_2026-06.parquet 28532120
Alta10_Turbine_Points_10m_2026-07.parquet 23000421
Alta10_Turbine_Points_10m_2026-08.parquet 28144042
Alta10_Turbine_Points_10m_2026-09.parquet 24499214

In [14]:
turbine_files = [
    file for file in parquet_files
    if "Turbine_Points" in file
]

print(turbine_files[0])

../../data/raw\Alta10_Turbine_Points_10m_2026-01.parquet

In [15]:
df1 = pd.read_parquet(turbine_files[0])

print(df1.shape)
df1.head()

(4464, 799)

,utcTime,ALTA10-SCEWF-WTG150-AirDensity,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient-Merged,ALTA10-SCEWF-WTG150-KPI-RealPowerAC,ALTA10-SCEWF-WTG150-KPI-TheoreticalPower,ALTA10-SCEWF-WTG150-KPI-WindSpeed,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient,ALTA10-SCEWF-WTG150-RealPowerAC,ALTA10-SCEWF-WTG150-NacellePosition,ALTA10-SCEWF-WTG150-BladePosition2,...,ALTA10-SCEWF-WTG197-NacellePosition,ALTA10-SCEWF-WTG197-BladePosition1,ALTA10-SCEWF-WTG197-BladePosition2,ALTA10-SCEWF-WTG197-BladePosition3,ALTA10-SCEWF-WTG197-BladeSetpointPosition1,ALTA10-SCEWF-WTG197-BladeSetpointPosition2,ALTA10-SCEWF-WTG197-BladeSetpointPosition3,ALTA10-SCEWF-WTG197-WindSpeed,ALTA10-SCEWF-WTG197-WindDirection,ALTA10-SCEWF-WTG197-WindDirectionRelative
DataTimeStamp,,,,,,,,,,,,,,,,,,,,,
2026-01-01 00:00:00,2026-01-01 08:00:00,1.092081,8.299405,672.60510,746.68463,6.906036,8.299405,670.286714,118.785714,-1.056245,...,62.500000,-0.15625,0.35788,-0.211483,-0.164664,0.369037,-0.207469,8.664497,54.739130,-6.454545
2026-01-01 00:10:00,2026-01-01 08:10:00,0.800856,8.573889,541.30096,466.00030,6.609679,8.573889,542.747853,117.066667,-1.077751,...,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,8.000924,52.763514,-5.510949
2026-01-01 00:20:00,2026-01-01 08:20:00,1.089478,8.972823,237.94884,292.86000,5.210308,8.972823,239.185173,118.812500,-0.445800,...,58.666667,NaN,NaN,NaN,NaN,NaN,NaN,8.207936,53.654930,-4.808824
2026-01-01 00:30:00,2026-01-01 08:30:00,0.800936,8.531316,503.22354,443.03992,6.510418,8.531316,504.556470,NaN,-1.205972,...,67.333333,NaN,NaN,NaN,NaN,NaN,NaN,8.099642,60.771812,-6.313869
2026-01-01 00:40:00,2026-01-01 08:40:00,1.090836,8.621079,444.42767,500.71185,6.093416,8.621079,444.157211,130.000000,-1.205672,...,67.100000,NaN,NaN,NaN,NaN,NaN,NaN,8.257563,60.806897,-6.318519

In [16]:
df1 = pd.read_parquet(turbine_files[0])

print(df1.shape)
print(df1.columns.tolist())

df1.head()

(4464, 799)

,utcTime,ALTA10-SCEWF-WTG150-AirDensity,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient-Merged,ALTA10-SCEWF-WTG150-KPI-RealPowerAC,ALTA10-SCEWF-WTG150-KPI-TheoreticalPower,ALTA10-SCEWF-WTG150-KPI-WindSpeed,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient,ALTA10-SCEWF-WTG150-RealPowerAC,ALTA10-SCEWF-WTG150-NacellePosition,ALTA10-SCEWF-WTG150-BladePosition2,...,ALTA10-SCEWF-WTG197-NacellePosition,ALTA10-SCEWF-WTG197-BladePosition1,ALTA10-SCEWF-WTG197-BladePosition2,ALTA10-SCEWF-WTG197-BladePosition3,ALTA10-SCEWF-WTG197-BladeSetpointPosition1,ALTA10-SCEWF-WTG197-BladeSetpointPosition2,ALTA10-SCEWF-WTG197-BladeSetpointPosition3,ALTA10-SCEWF-WTG197-WindSpeed,ALTA10-SCEWF-WTG197-WindDirection,ALTA10-SCEWF-WTG197-WindDirectionRelative
DataTimeStamp,,,,,,,,,,,,,,,,,,,,,
2026-01-01 00:00:00,2026-01-01 08:00:00,1.092081,8.299405,672.60510,746.68463,6.906036,8.299405,670.286714,118.785714,-1.056245,...,62.500000,-0.15625,0.35788,-0.211483,-0.164664,0.369037,-0.207469,8.664497,54.739130,-6.454545
2026-01-01 00:10:00,2026-01-01 08:10:00,0.800856,8.573889,541.30096,466.00030,6.609679,8.573889,542.747853,117.066667,-1.077751,...,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,8.000924,52.763514,-5.510949
2026-01-01 00:20:00,2026-01-01 08:20:00,1.089478,8.972823,237.94884,292.86000,5.210308,8.972823,239.185173,118.812500,-0.445800,...,58.666667,NaN,NaN,NaN,NaN,NaN,NaN,8.207936,53.654930,-4.808824
2026-01-01 00:30:00,2026-01-01 08:30:00,0.800936,8.531316,503.22354,443.03992,6.510418,8.531316,504.556470,NaN,-1.205972,...,67.333333,NaN,NaN,NaN,NaN,NaN,NaN,8.099642,60.771812,-6.313869
2026-01-01 00:40:00,2026-01-01 08:40:00,1.090836,8.621079,444.42767,500.71185,6.093416,8.621079,444.157211,130.000000,-1.205672,...,67.100000,NaN,NaN,NaN,NaN,NaN,NaN,8.257563,60.806897,-6.318519

In [17]:
df = pd.concat(
    [pd.read_parquet(file) for file in turbine_files],
    ignore_index=True
)

In [18]:
df.head()

,utcTime,ALTA10-SCEWF-WTG150-AirDensity,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient-Merged,ALTA10-SCEWF-WTG150-KPI-RealPowerAC,ALTA10-SCEWF-WTG150-KPI-TheoreticalPower,ALTA10-SCEWF-WTG150-KPI-WindSpeed,ALTA10-SCEWF-WTG150-KPI-TemperatureAmbient,ALTA10-SCEWF-WTG150-RealPowerAC,ALTA10-SCEWF-WTG150-NacellePosition,ALTA10-SCEWF-WTG150-BladePosition2,...,ALTA10-SCEWF-WTG197-NacellePosition,ALTA10-SCEWF-WTG197-BladePosition1,ALTA10-SCEWF-WTG197-BladePosition2,ALTA10-SCEWF-WTG197-BladePosition3,ALTA10-SCEWF-WTG197-BladeSetpointPosition1,ALTA10-SCEWF-WTG197-BladeSetpointPosition2,ALTA10-SCEWF-WTG197-BladeSetpointPosition3,ALTA10-SCEWF-WTG197-WindSpeed,ALTA10-SCEWF-WTG197-WindDirection,ALTA10-SCEWF-WTG197-WindDirectionRelative
0,2026-01-01 08:00:00,1.092081,8.299405,672.60510,746.68463,6.906036,8.299405,670.286714,118.785714,-1.056245,...,62.500000,-0.15625,0.35788,-0.211483,-0.164664,0.369037,-0.207469,8.664497,54.739130,-6.454545
1,2026-01-01 08:10:00,0.800856,8.573889,541.30096,466.00030,6.609679,8.573889,542.747853,117.066667,-1.077751,...,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,8.000924,52.763514,-5.510949
2,2026-01-01 08:20:00,1.089478,8.972823,237.94884,292.86000,5.210308,8.972823,239.185173,118.812500,-0.445800,...,58.666667,NaN,NaN,NaN,NaN,NaN,NaN,8.207936,53.654930,-4.808824
3,2026-01-01 08:30:00,0.800936,8.531316,503.22354,443.03992,6.510418,8.531316,504.556470,NaN,-1.205972,...,67.333333,NaN,NaN,NaN,NaN,NaN,NaN,8.099642,60.771812,-6.313869
4,2026-01-01 08:40:00,1.090836,8.621079,444.42767,500.71185,6.093416,8.621079,444.157211,130.000000,-1.205672,...,67.100000,NaN,NaN,NaN,NaN,NaN,NaN,8.257563,60.806897,-6.318519

In [19]:
import re

def clean_column(col):
    # special case
    if col == "utcTime":
        return "utc_time"

    # remove the common site prefix
    col = col.replace("ALTA10-SCEWF-", "")

    # remove KPI marker
    col = col.replace("-KPI-", "-")

    # replace remaining hyphens with underscores
    col = col.replace("-", "_")

    # convert CamelCase to snake_case
    col = re.sub(r'(?<!^)(?=[A-Z])', '_', col)

    # clean up duplicate underscores and lowercase everything
    col = re.sub(r'_+', '_', col).lower()

    return col

df1.columns = [clean_column(col) for col in df1.columns]

In [20]:
df1.columns.tolist()

['utc_time',
 'w_t_g150_air_density',
 'w_t_g150_temperature_ambient_merged',
 'w_t_g150_real_power_a_c',
 'w_t_g150_theoretical_power',
 'w_t_g150_wind_speed',
 'w_t_g150_temperature_ambient',
 'w_t_g150_real_power_a_c',
 'w_t_g150_nacelle_position',
 'w_t_g150_blade_position2',
 'w_t_g150_blade_position3',
 'w_t_g150_blade_setpoint_position1',
 'w_t_g150_blade_setpoint_position2',
 'w_t_g150_blade_setpoint_position3',
 'w_t_g150_wind_speed',
 'w_t_g150_wind_direction',
 'w_t_g150_wind_direction_relative',
 'w_t_g151_air_density',
 'w_t_g151_temperature_ambient_merged',
 'w_t_g151_real_power_a_c',
 'w_t_g151_theoretical_power',
 'w_t_g151_wind_speed',
 'w_t_g151_temperature_ambient',
 'w_t_g151_real_power_a_c',
 'w_t_g151_nacelle_position',
 'w_t_g151_blade_position1',
 'w_t_g151_blade_position2',
 'w_t_g151_blade_position3',
 'w_t_g151_blade_setpoint_position1',
 'w_t_g151_blade_setpoint_position2',
 'w_t_g151_blade_setpoint_position3',
 'w_t_g151_wind_speed',
 'w_t_g151_wind_direction',
 'w_t_g151_wind_direction_relative',
 'w_t_g152_air_density',
 'w_t_g152_temperature_ambient_merged',
 'w_t_g152_real_power_a_c',
 'w_t_g152_theoretical_power',
 'w_t_g152_wind_speed',
 'w_t_g152_temperature_ambient',
 'w_t_g152_real_power_a_c',
 'w_t_g152_nacelle_position',
 'w_t_g152_blade_position1',
 'w_t_g152_blade_position2',
 'w_t_g152_blade_position3',
 'w_t_g152_blade_setpoint_position1',
 'w_t_g152_blade_setpoint_position2',
 'w_t_g152_blade_setpoint_position3',
 'w_t_g152_wind_speed',
 'w_t_g152_wind_direction',
 'w_t_g152_wind_direction_relative',
 'w_t_g153_air_density',
 'w_t_g153_temperature_ambient_merged',
 'w_t_g153_real_power_a_c',
 'w_t_g153_theoretical_power',
 'w_t_g153_wind_speed',
 'w_t_g153_temperature_ambient',
 'w_t_g153_real_power_a_c',
 'w_t_g153_nacelle_position',
 'w_t_g153_blade_position1',
 'w_t_g153_blade_position2',
 'w_t_g153_blade_position3',
 'w_t_g153_blade_setpoint_position1',
 'w_t_g153_blade_setpoint_position2',
 'w_t_g153_blade_setpoint_position3',
 'w_t_g153_wind_speed',
 'w_t_g153_wind_direction',
 'w_t_g153_wind_direction_relative',
 'w_t_g154_air_density',
 'w_t_g154_temperature_ambient_merged',
 'w_t_g154_real_power_a_c',
 'w_t_g154_theoretical_power',
 'w_t_g154_wind_speed',
 'w_t_g154_temperature_ambient',
 'w_t_g154_real_power_a_c',
 'w_t_g154_nacelle_position',
 'w_t_g154_blade_position1',
 'w_t_g154_blade_position2',
 'w_t_g154_blade_position3',
 'w_t_g154_blade_setpoint_position1',
 'w_t_g154_blade_setpoint_position2',
 'w_t_g154_blade_setpoint_position3',
 'w_t_g154_wind_speed',
 'w_t_g154_wind_direction',
 'w_t_g154_wind_direction_relative',
 'w_t_g155_air_density',
 'w_t_g155_temperature_ambient_merged',
 'w_t_g155_real_power_a_c',
 'w_t_g155_theoretical_power',
 'w_t_g155_wind_speed',
 'w_t_g155_temperature_ambient',
 'w_t_g155_real_power_a_c',
 'w_t_g155_nacelle_position',
 'w_t_g155_blade_position1',
 'w_t_g155_blade_position2',
 'w_t_g155_blade_position3',
 'w_t_g155_blade_setpoint_position1',
 'w_t_g155_blade_setpoint_position2',
 'w_t_g155_blade_setpoint_position3',
 'w_t_g155_wind_speed',
 'w_t_g155_wind_direction',
 'w_t_g155_wind_direction_relative',
 'w_t_g156_air_density',
 'w_t_g156_temperature_ambient_merged',
 'w_t_g156_real_power_a_c',
 'w_t_g156_theoretical_power',
 'w_t_g156_wind_speed',
 'w_t_g156_temperature_ambient',
 'w_t_g156_real_power_a_c',
 'w_t_g156_nacelle_position',
 'w_t_g156_blade_position1',
 'w_t_g156_blade_position2',
 'w_t_g156_blade_position3',
 'w_t_g156_blade_setpoint_position1',
 'w_t_g156_blade_setpoint_position2',
 'w_t_g156_blade_setpoint_position3',
 'w_t_g156_wind_speed',
 'w_t_g156_wind_direction',
 'w_t_g156_wind_direction_relative',
 'w_t_g157_air_density',
 'w_t_g157_temperature_ambient_merged',
 'w_t_g157_real_power_a_c',
 'w_t_g157_theoretical_power',
 'w_t_g157_wind_speed',
 'w_t_g157_temperature_ambient',
 'w_t_g157_real_power_a_c',
 'w_t_g157_nacelle_position',
 'w_t_g157_blade_position1',
 'w_t_g157_blade_position2',
 'w_t_g157_blade_position3',
 'w_t_g157_blade_setpoint_position1',
 'w_t_g157_blade_setpoint_position2',
 'w_t_g157_blade_setpoint_position3',
 'w_t_g157_wind_speed',
 'w_t_g157_wind_direction',
 'w_t_g157_wind_direction_relative',
 'w_t_g158_air_density',
 'w_t_g158_temperature_ambient_merged',
 'w_t_g158_real_power_a_c',
 'w_t_g158_theoretical_power',
 'w_t_g158_wind_speed',
 'w_t_g158_temperature_ambient',
 'w_t_g158_real_power_a_c',
 'w_t_g158_nacelle_position',
 'w_t_g158_blade_position1',
 'w_t_g158_blade_position2',
 'w_t_g158_blade_position3',
 'w_t_g158_blade_setpoint_position1',
 'w_t_g158_blade_setpoint_position2',
 'w_t_g158_blade_setpoint_position3',
 'w_t_g158_wind_speed',
 'w_t_g158_wind_direction',
 'w_t_g158_wind_direction_relative',
 'w_t_g159_air_density',
 'w_t_g159_temperature_ambient_merged',
 'w_t_g159_real_power_a_c',
 'w_t_g159_theoretical_power',
 'w_t_g159_wind_speed',
 'w_t_g159_temperature_ambient',
 'w_t_g159_real_power_a_c',
 'w_t_g159_nacelle_position',
 'w_t_g159_blade_position1',
 'w_t_g159_blade_position2',
 'w_t_g159_blade_position3',
 'w_t_g159_blade_setpoint_position1',
 'w_t_g159_blade_setpoint_position2',
 'w_t_g159_blade_setpoint_position3',
 'w_t_g159_wind_speed',
 'w_t_g159_wind_direction',
 'w_t_g159_wind_direction_relative',
 'w_t_g161_air_density',
 'w_t_g161_temperature_ambient_merged',
 'w_t_g161_real_power_a_c',
 'w_t_g161_theoretical_power',
 'w_t_g161_wind_speed',
 'w_t_g161_temperature_ambient',
 'w_t_g161_real_power_a_c',
 'w_t_g161_nacelle_position',
 'w_t_g161_blade_position1',
 'w_t_g161_blade_position2',
 'w_t_g161_blade_position3',
 'w_t_g161_blade_setpoint_position1',
 'w_t_g161_blade_setpoint_position2',
 'w_t_g161_blade_setpoint_position3',
 'w_t_g161_wind_speed',
 'w_t_g161_wind_direction',
 'w_t_g161_wind_direction_relative',
 'w_t_g162_air_density',
 'w_t_g162_temperature_ambient_merged',
 'w_t_g162_real_power_a_c',
 'w_t_g162_theoretical_power',
 'w_t_g162_wind_speed',
 'w_t_g162_temperature_ambient',
 'w_t_g162_real_power_a_c',
 'w_t_g162_nacelle_position',
 'w_t_g162_blade_position1',
 'w_t_g162_blade_position2',
 'w_t_g162_blade_position3',
 'w_t_g162_blade_setpoint_position1',
 'w_t_g162_blade_setpoint_position2',
 'w_t_g162_blade_setpoint_position3',
 'w_t_g162_wind_speed',
 'w_t_g162_wind_direction',
 'w_t_g162_wind_direction_relative',
 'w_t_g163_air_density',
 'w_t_g163_temperature_ambient_merged',
 'w_t_g163_real_power_a_c',
 'w_t_g163_theoretical_power',
 'w_t_g163_wind_speed',
 'w_t_g163_temperature_ambient',
 'w_t_g163_real_power_a_c',
 'w_t_g163_nacelle_position',
 'w_t_g163_blade_position1',
 'w_t_g163_blade_position2',
 'w_t_g163_blade_position3',
 'w_t_g163_blade_setpoint_position1',
 'w_t_g163_blade_setpoint_position2',
 'w_t_g163_blade_setpoint_position3',
 'w_t_g163_wind_speed',
 'w_t_g163_wind_direction',
 'w_t_g163_wind_direction_relative',
 'w_t_g164_air_density',
 'w_t_g164_temperature_ambient_merged',
 'w_t_g164_real_power_a_c',
 'w_t_g164_theoretical_power',
 'w_t_g164_wind_speed',
 'w_t_g164_temperature_ambient',
 'w_t_g164_real_power_a_c',
 'w_t_g164_nacelle_position',
 'w_t_g164_blade_position1',
 'w_t_g164_blade_position2',
 'w_t_g164_blade_position3',
 'w_t_g164_blade_setpoint_position1',
 'w_t_g164_blade_setpoint_position2',
 'w_t_g164_blade_setpoint_position3',
 'w_t_g164_wind_speed',
 'w_t_g164_wind_direction',
 'w_t_g164_wind_direction_relative',
 'w_t_g165_air_density',
 'w_t_g165_temperature_ambient_merged',
 'w_t_g165_real_power_a_c',
 'w_t_g165_theoretical_power',
 'w_t_g165_wind_speed',
 'w_t_g165_temperature_ambient',
 'w_t_g165_real_power_a_c',
 'w_t_g165_nacelle_position',
 'w_t_g165_blade_position1',
 'w_t_g165_blade_position2',
 'w_t_g165_blade_position3',
 'w_t_g165_blade_setpoint_position1',
 'w_t_g165_blade_setpoint_position2',
 'w_t_g165_blade_setpoint_position3',
 'w_t_g165_wind_speed',
 'w_t_g165_wind_direction',
 'w_t_g165_wind_direction_relative',
 'w_t_g166_air_density',
 'w_t_g166_temperature_ambient_merged',
 'w_t_g166_real_power_a_c',
 'w_t_g166_theoretical_power',
 'w_t_g166_wind_speed',
 'w_t_g166_temperature_ambient',
 'w_t_g166_real_power_a_c',
 'w_t_g166_nacelle_position',
 'w_t_g166_blade_position1',
 'w_t_g166_blade_position2',
 'w_t_g166_blade_position3',
 'w_t_g166_blade_setpoint_position1',
 'w_t_g166_blade_setpoint_position2',
 'w_t_g166_blade_setpoint_position3',
 'w_t_g166_wind_speed',
 'w_t_g166_wind_direction',
 'w_t_g166_wind_direction_relative',
 'w_t_g167_air_density',
 'w_t_g167_temperature_ambient_merged',
 'w_t_g167_real_power_a_c',
 'w_t_g167_theoretical_power',
 'w_t_g167_wind_speed',
 'w_t_g167_temperature_ambient',
 'w_t_g167_real_power_a_c',
 'w_t_g167_nacelle_position',
 'w_t_g167_blade_position1',
 'w_t_g167_blade_position2',
 'w_t_g167_blade_position3',
 'w_t_g167_blade_setpoint_position1',
 'w_t_g167_blade_setpoint_position2',
 'w_t_g167_blade_setpoint_position3',
 'w_t_g167_wind_speed',
 'w_t_g167_wind_direction',
 'w_t_g167_wind_direction_relative',
 'w_t_g168_air_density',
 'w_t_g168_temperature_ambient_merged',
 'w_t_g168_real_power_a_c',
 'w_t_g168_theoretical_power',
 'w_t_g168_wind_speed',
 'w_t_g168_temperature_ambient',
 'w_t_g168_real_power_a_c',
 'w_t_g168_nacelle_position',
 'w_t_g168_blade_position1',
 'w_t_g168_blade_position2',
 'w_t_g168_blade_position3',
 'w_t_g168_blade_setpoint_position1',
 'w_t_g168_blade_setpoint_position2',
 'w_t_g168_blade_setpoint_position3',
 'w_t_g168_wind_speed',
 'w_t_g168_wind_direction',
 'w_t_g168_wind_direction_relative',
 'w_t_g169_air_density',
 'w_t_g169_temperature_ambient_merged',
 'w_t_g169_real_power_a_c',
 'w_t_g169_theoretical_power',
 'w_t_g169_wind_speed',
 'w_t_g169_temperature_ambient',
 'w_t_g169_real_power_a_c',
 'w_t_g169_nacelle_position',
 'w_t_g169_blade_position1',
 'w_t_g169_blade_position2',
 'w_t_g169_blade_position3',
 'w_t_g169_blade_setpoint_position1',
 'w_t_g169_blade_setpoint_position2',
 'w_t_g169_blade_setpoint_position3',
 'w_t_g169_wind_speed',
 'w_t_g169_wind_direction',
 'w_t_g169_wind_direction_relative',
 'w_t_g170_air_density',
 'w_t_g170_temperature_ambient_merged',
 'w_t_g170_real_power_a_c',
 'w_t_g170_theoretical_power',
 'w_t_g170_wind_speed',
 'w_t_g170_temperature_ambient',
 'w_t_g170_real_power_a_c',
 'w_t_g170_nacelle_position',
 'w_t_g170_blade_position1',
 'w_t_g170_blade_position2',
 'w_t_g170_blade_position3',
 'w_t_g170_blade_setpoint_position1',
 'w_t_g170_blade_setpoint_position2',
 'w_t_g170_blade_setpoint_position3',
 'w_t_g170_wind_speed',
 'w_t_g170_wind_direction',
 'w_t_g170_wind_direction_relative',
 'w_t_g171_air_density',
 'w_t_g171_temperature_ambient_merged',
 'w_t_g171_real_power_a_c',
 'w_t_g171_theoretical_power',
 'w_t_g171_wind_speed',
 'w_t_g171_temperature_ambient',
 'w_t_g171_real_power_a_c',
 'w_t_g171_nacelle_position',
 'w_t_g171_blade_position1',
 'w_t_g171_blade_position2',
 'w_t_g171_blade_position3',
 'w_t_g171_blade_setpoint_position1',
 'w_t_g171_blade_setpoint_position2',
 'w_t_g171_blade_setpoint_position3',
 'w_t_g171_wind_speed',
 'w_t_g171_wind_direction',
 'w_t_g171_wind_direction_relative',
 'w_t_g172_air_density',
 'w_t_g172_temperature_ambient_merged',
 'w_t_g172_real_power_a_c',
 'w_t_g172_theoretical_power',
 'w_t_g172_wind_speed',
 'w_t_g172_temperature_ambient',
 'w_t_g172_real_power_a_c',
 'w_t_g172_nacelle_position',
 'w_t_g172_blade_position1',
 'w_t_g172_blade_position2',
 'w_t_g172_blade_position3',
 'w_t_g172_blade_setpoint_position1',
 'w_t_g172_blade_setpoint_position2',
 'w_t_g172_blade_setpoint_position3',
 'w_t_g172_wind_speed',
 'w_t_g172_wind_direction',
 'w_t_g172_wind_direction_relative',
 'w_t_g173_air_density',
 'w_t_g173_temperature_ambient_merged',
 'w_t_g173_real_power_a_c',
 'w_t_g173_theoretical_power',
 'w_t_g173_wind_speed',
 'w_t_g173_temperature_ambient',
 'w_t_g173_real_power_a_c',
 'w_t_g173_nacelle_position',
 'w_t_g173_blade_position1',
 'w_t_g173_blade_position2',
 'w_t_g173_blade_position3',
 'w_t_g173_blade_setpoint_position1',
 'w_t_g173_blade_setpoint_position2',
 'w_t_g173_blade_setpoint_position3',
 'w_t_g173_wind_speed',
 'w_t_g173_wind_direction',
 'w_t_g173_wind_direction_relative',
 'w_t_g174_air_density',
 'w_t_g174_temperature_ambient_merged',
 'w_t_g174_real_power_a_c',
 'w_t_g174_theoretical_power',
 'w_t_g174_wind_speed',
 'w_t_g174_temperature_ambient',
 'w_t_g174_real_power_a_c',
 'w_t_g174_nacelle_position',
 'w_t_g174_blade_position1',
 'w_t_g174_blade_position2',
 'w_t_g174_blade_position3',
 'w_t_g174_blade_setpoint_position1',
 'w_t_g174_blade_setpoint_position2',
 'w_t_g174_blade_setpoint_position3',
 'w_t_g174_wind_speed',
 'w_t_g174_wind_direction',
 'w_t_g174_wind_direction_relative',
 'w_t_g175_air_density',
 'w_t_g175_temperature_ambient_merged',
 'w_t_g175_real_power_a_c',
 'w_t_g175_theoretical_power',
 'w_t_g175_wind_speed',
 'w_t_g175_temperature_ambient',
 'w_t_g175_real_power_a_c',
 'w_t_g175_nacelle_position',
 'w_t_g175_blade_position1',
 'w_t_g175_blade_position2',
 'w_t_g175_blade_position3',
 'w_t_g175_blade_setpoint_position1',
 'w_t_g175_blade_setpoint_position2',
 'w_t_g175_blade_setpoint_position3',
 'w_t_g175_wind_speed',
 'w_t_g175_wind_direction',
 'w_t_g175_wind_direction_relative',
 'w_t_g176_air_density',
 'w_t_g176_temperature_ambient_merged',
 'w_t_g176_real_power_a_c',
 'w_t_g176_theoretical_power',
 'w_t_g176_wind_speed',
 'w_t_g176_temperature_ambient',
 'w_t_g176_real_power_a_c',
 'w_t_g176_nacelle_position',
 'w_t_g176_blade_position1',
 'w_t_g176_blade_position2',
 'w_t_g176_blade_position3',
 'w_t_g176_blade_setpoint_position1',
 'w_t_g176_blade_setpoint_position2',
 'w_t_g176_blade_setpoint_position3',
 'w_t_g176_wind_speed',
 'w_t_g176_wind_direction',
 'w_t_g176_wind_direction_relative',
 'w_t_g177_air_density',
 'w_t_g177_temperature_ambient_merged',
 'w_t_g177_real_power_a_c',
 'w_t_g177_theoretical_power',
 'w_t_g177_wind_speed',
 'w_t_g177_temperature_ambient',
 'w_t_g177_real_power_a_c',
 'w_t_g177_nacelle_position',
 'w_t_g177_blade_position1',
 'w_t_g177_blade_position2',
 'w_t_g177_blade_position3',
 'w_t_g177_blade_setpoint_position1',
 'w_t_g177_blade_setpoint_position2',
 'w_t_g177_blade_setpoint_position3',
 'w_t_g177_wind_speed',
 'w_t_g177_wind_direction',
 'w_t_g177_wind_direction_relative',
 'w_t_g178_air_density',
 'w_t_g178_temperature_ambient_merged',
 'w_t_g178_real_power_a_c',
 'w_t_g178_theoretical_power',
 'w_t_g178_wind_speed',
 'w_t_g178_temperature_ambient',
 'w_t_g178_real_power_a_c',
 'w_t_g178_nacelle_position',
 'w_t_g178_blade_position1',
 'w_t_g178_blade_position2',
 'w_t_g178_blade_position3',
 'w_t_g178_blade_setpoint_position1',
 'w_t_g178_blade_setpoint_position2',
 'w_t_g178_blade_setpoint_position3',
 'w_t_g178_wind_speed',
 'w_t_g178_wind_direction',
 'w_t_g178_wind_direction_relative',
 'w_t_g179_air_density',
 'w_t_g179_temperature_ambient_merged',
 'w_t_g179_real_power_a_c',
 'w_t_g179_theoretical_power',
 'w_t_g179_wind_speed',
 'w_t_g179_temperature_ambient',
 'w_t_g179_real_power_a_c',
 'w_t_g179_nacelle_position',
 'w_t_g179_blade_position1',
 'w_t_g179_blade_position2',
 'w_t_g179_blade_position3',
 'w_t_g179_blade_setpoint_position1',
 'w_t_g179_blade_setpoint_position2',
 'w_t_g179_blade_setpoint_position3',
 'w_t_g179_wind_speed',
 'w_t_g179_wind_direction',
 'w_t_g179_wind_direction_relative',
 'w_t_g180_air_density',
 'w_t_g180_temperature_ambient_merged',
 'w_t_g180_real_power_a_c',
 'w_t_g180_theoretical_power',
 'w_t_g180_wind_speed',
 'w_t_g180_temperature_ambient',
 'w_t_g180_real_power_a_c',
 'w_t_g180_nacelle_position',
 'w_t_g180_blade_position1',
 'w_t_g180_blade_position2',
 'w_t_g180_blade_position3',
 'w_t_g180_blade_setpoint_position1',
 'w_t_g180_blade_setpoint_position2',
 'w_t_g180_blade_setpoint_position3',
 'w_t_g180_wind_speed',
 'w_t_g180_wind_direction',
 'w_t_g180_wind_direction_relative',
 'w_t_g181_air_density',
 'w_t_g181_temperature_ambient_merged',
 'w_t_g181_real_power_a_c',
 'w_t_g181_theoretical_power',
 'w_t_g181_wind_speed',
 'w_t_g181_temperature_ambient',
 'w_t_g181_real_power_a_c',
 'w_t_g181_nacelle_position',
 'w_t_g181_blade_position1',
 'w_t_g181_blade_position2',
 'w_t_g181_blade_position3',
 'w_t_g181_blade_setpoint_position1',
 'w_t_g181_blade_setpoint_position2',
 'w_t_g181_blade_setpoint_position3',
 'w_t_g181_wind_speed',
 'w_t_g181_wind_direction',
 'w_t_g181_wind_direction_relative',
 'w_t_g182_air_density',
 'w_t_g182_temperature_ambient_merged',
 'w_t_g182_real_power_a_c',
 'w_t_g182_theoretical_power',
 'w_t_g182_wind_speed',
 'w_t_g182_temperature_ambient',
 'w_t_g182_real_power_a_c',
 'w_t_g182_nacelle_position',
 'w_t_g182_blade_position1',
 'w_t_g182_blade_position2',
 'w_t_g182_blade_position3',
 'w_t_g182_blade_setpoint_position1',
 'w_t_g182_blade_setpoint_position2',
 'w_t_g182_blade_setpoint_position3',
 'w_t_g182_wind_speed',
 'w_t_g182_wind_direction',
 'w_t_g182_wind_direction_relative',
 'w_t_g183_air_density',
 'w_t_g183_temperature_ambient_merged',
 'w_t_g183_real_power_a_c',
 'w_t_g183_theoretical_power',
 'w_t_g183_wind_speed',
 'w_t_g183_temperature_ambient',
 'w_t_g183_real_power_a_c',
 'w_t_g183_nacelle_position',
 'w_t_g183_blade_position1',
 'w_t_g183_blade_position2',
 'w_t_g183_blade_position3',
 'w_t_g183_blade_setpoint_position1',
 'w_t_g183_blade_setpoint_position2',
 'w_t_g183_blade_setpoint_position3',
 'w_t_g183_wind_speed',
 'w_t_g183_wind_direction',
 'w_t_g183_wind_direction_relative',
 'w_t_g184_air_density',
 'w_t_g184_temperature_ambient_merged',
 'w_t_g184_real_power_a_c',
 'w_t_g184_theoretical_power',
 'w_t_g184_wind_speed',
 'w_t_g184_temperature_ambient',
 'w_t_g184_real_power_a_c',
 'w_t_g184_nacelle_position',
 'w_t_g184_blade_position1',
 'w_t_g184_blade_position2',
 'w_t_g184_blade_position3',
 'w_t_g184_blade_setpoint_position1',
 'w_t_g184_blade_setpoint_position2',
 'w_t_g184_blade_setpoint_position3',
 'w_t_g184_wind_speed',
 'w_t_g184_wind_direction',
 'w_t_g184_wind_direction_relative',
 'w_t_g185_air_density',
 'w_t_g185_temperature_ambient_merged',
 'w_t_g185_real_power_a_c',
 'w_t_g185_theoretical_power',
 'w_t_g185_wind_speed',
 'w_t_g185_temperature_ambient',
 'w_t_g185_real_power_a_c',
 'w_t_g185_nacelle_position',
 'w_t_g185_blade_position1',
 'w_t_g185_blade_position2',
 'w_t_g185_blade_position3',
 'w_t_g185_blade_setpoint_position1',
 'w_t_g185_blade_setpoint_position2',
 'w_t_g185_blade_setpoint_position3',
 'w_t_g185_wind_speed',
 'w_t_g185_wind_direction',
 'w_t_g185_wind_direction_relative',
 'w_t_g186_air_density',
 'w_t_g186_temperature_ambient_merged',
 'w_t_g186_real_power_a_c',
 'w_t_g186_theoretical_power',
 'w_t_g186_wind_speed',
 'w_t_g186_temperature_ambient',
 'w_t_g186_real_power_a_c',
 'w_t_g186_nacelle_position',
 'w_t_g186_blade_position1',
 'w_t_g186_blade_position2',
 'w_t_g186_blade_position3',
 'w_t_g186_blade_setpoint_position1',
 'w_t_g186_blade_setpoint_position2',
 'w_t_g186_blade_setpoint_position3',
 'w_t_g186_wind_speed',
 'w_t_g186_wind_direction',
 'w_t_g186_wind_direction_relative',
 'w_t_g187_air_density',
 'w_t_g187_temperature_ambient_merged',
 'w_t_g187_real_power_a_c',
 'w_t_g187_theoretical_power',
 'w_t_g187_wind_speed',
 'w_t_g187_temperature_ambient',
 'w_t_g187_real_power_a_c',
 'w_t_g187_nacelle_position',
 'w_t_g187_blade_position1',
 'w_t_g187_blade_position2',
 'w_t_g187_blade_position3',
 'w_t_g187_blade_setpoint_position1',
 'w_t_g187_blade_setpoint_position2',
 'w_t_g187_blade_setpoint_position3',
 'w_t_g187_wind_speed',
 'w_t_g187_wind_direction',
 'w_t_g187_wind_direction_relative',
 'w_t_g188_air_density',
 'w_t_g188_temperature_ambient_merged',
 'w_t_g188_real_power_a_c',
 'w_t_g188_theoretical_power',
 'w_t_g188_wind_speed',
 'w_t_g188_temperature_ambient',
 'w_t_g188_real_power_a_c',
 'w_t_g188_nacelle_position',
 'w_t_g188_blade_position1',
 'w_t_g188_blade_position2',
 'w_t_g188_blade_position3',
 'w_t_g188_blade_setpoint_position1',
 'w_t_g188_blade_setpoint_position2',
 'w_t_g188_blade_setpoint_position3',

In [21]:
df1.head()

,utc_time,w_t_g150_air_density,w_t_g150_temperature_ambient_merged,w_t_g150_real_power_a_c,w_t_g150_theoretical_power,w_t_g150_wind_speed,w_t_g150_temperature_ambient,w_t_g150_real_power_a_c,w_t_g150_nacelle_position,w_t_g150_blade_position2,...,w_t_g197_nacelle_position,w_t_g197_blade_position1,w_t_g197_blade_position2,w_t_g197_blade_position3,w_t_g197_blade_setpoint_position1,w_t_g197_blade_setpoint_position2,w_t_g197_blade_setpoint_position3,w_t_g197_wind_speed,w_t_g197_wind_direction,w_t_g197_wind_direction_relative
DataTimeStamp,,,,,,,,,,,,,,,,,,,,,
2026-01-01 00:00:00,2026-01-01 08:00:00,1.092081,8.299405,672.60510,746.68463,6.906036,8.299405,670.286714,118.785714,-1.056245,...,62.500000,-0.15625,0.35788,-0.211483,-0.164664,0.369037,-0.207469,8.664497,54.739130,-6.454545
2026-01-01 00:10:00,2026-01-01 08:10:00,0.800856,8.573889,541.30096,466.00030,6.609679,8.573889,542.747853,117.066667,-1.077751,...,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,8.000924,52.763514,-5.510949
2026-01-01 00:20:00,2026-01-01 08:20:00,1.089478,8.972823,237.94884,292.86000,5.210308,8.972823,239.185173,118.812500,-0.445800,...,58.666667,NaN,NaN,NaN,NaN,NaN,NaN,8.207936,53.654930,-4.808824
2026-01-01 00:30:00,2026-01-01 08:30:00,0.800936,8.531316,503.22354,443.03992,6.510418,8.531316,504.556470,NaN,-1.205972,...,67.333333,NaN,NaN,NaN,NaN,NaN,NaN,8.099642,60.771812,-6.313869
2026-01-01 00:40:00,2026-01-01 08:40:00,1.090836,8.621079,444.42767,500.71185,6.093416,8.621079,444.157211,130.000000,-1.205672,...,67.100000,NaN,NaN,NaN,NaN,NaN,NaN,8.257563,60.806897,-6.318519

In [22]:
missing = df1.isna().sum().sort_values(ascending=False)

print(missing)

w_t_g169_real_power_a_c                3821
w_t_g169_blade_setpoint_position1      3704
w_t_g169_blade_setpoint_position3      3704
w_t_g169_blade_setpoint_position2      3704
w_t_g169_blade_position3               3702
                                       ...
w_t_g195_temperature_ambient_merged       0
w_t_g195_theoretical_power                0
w_t_g153_air_density                      0
w_t_g153_temperature_ambient_merged       0
w_t_g153_theoretical_power                0
Length: 799, dtype: int64

In [24]:
missing_summary = pd.DataFrame({
    "missing_count": df1.isna().sum(),
    "missing_percent": df1.isna().mean() * 100
}).sort_values("missing_percent", ascending=False)

missing_summary

                                     missing_count  missing_percent
w_t_g169_real_power_a_c                       3821        85.595878
w_t_g169_blade_setpoint_position1             3704        82.974910
w_t_g169_blade_setpoint_position3             3704        82.974910
w_t_g169_blade_setpoint_position2             3704        82.974910
w_t_g169_blade_position3                      3702        82.930108
...                                            ...              ...
w_t_g195_temperature_ambient_merged              0         0.000000
w_t_g195_theoretical_power                       0         0.000000
w_t_g153_air_density                             0         0.000000
w_t_g153_temperature_ambient_merged              0         0.000000
w_t_g153_theoretical_power                       0         0.000000

[799 rows x 2 columns]

In [25]:
missing_pct = df1.isna().mean() * 100

low_missing = missing_pct[missing_pct < 5]
medium_missing = missing_pct[(missing_pct >= 5) & (missing_pct < 50)]
high_missing = missing_pct[missing_pct >= 50]

print("Low missing:", len(low_missing))
print("Medium missing:", len(medium_missing))
print("High missing:", len(high_missing))

Low missing: 418
Medium missing: 225
High missing: 156

In [26]:
high_missing.sort_values(ascending=False)

w_t_g169_real_power_a_c              85.595878
w_t_g169_blade_setpoint_position1    82.974910
w_t_g169_blade_setpoint_position3    82.974910
w_t_g169_blade_setpoint_position2    82.974910
w_t_g169_blade_position3             82.930108
                                       ...
w_t_g181_blade_setpoint_position3    50.492832
w_t_g197_blade_position3             50.448029
w_t_g196_blade_position2             50.246416
w_t_g196_blade_position3             50.156810
w_t_g196_blade_position1             50.022401
Length: 156, dtype: float64

In [27]:
import pandas as pd
import re

# --------------------------------------------------
# 1. CLEAN COLUMN NAMES
# --------------------------------------------------

def clean_column(col):
    # Special case for time column
    if col == "utcTime":
        return "utc_time"

    # Remove site prefix
    col = col.replace("ALTA10-SCEWF-", "")

    # Remove KPI marker
    col = col.replace("-KPI-", "-")

    # WTG169 -> wtg169 without splitting W_T_G
    col = re.sub(r'WTG(\d+)', r'wtg\1', col)

    # Replace hyphens with underscores
    col = col.replace("-", "_")

    # Convert CamelCase to snake_case
    col = re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', col)

    # Add underscore before trailing position numbers
    col = re.sub(r'([A-Za-z])(\d+)$', r'\1_\2', col)

    # Clean duplicates and lowercase
    col = re.sub(r'_+', '_', col).lower().strip('_')

    return col


# Make a copy so df1 remains untouched
df_clean = df1.copy()

# Clean the column names
df_clean.columns = [clean_column(col) for col in df_clean.columns]


# --------------------------------------------------
# 2. CALCULATE MISSING DATA
# --------------------------------------------------

missing_summary = pd.DataFrame({
    "missing_count": df_clean.isna().sum(),
    "missing_percent": df_clean.isna().mean() * 100
}).sort_values("missing_percent", ascending=False)


# --------------------------------------------------
# 3. CHOOSE A THRESHOLD
# --------------------------------------------------

threshold = 80   # hide columns with more than 80% missing


# Identify them, but DO NOT delete them from df_clean
high_missing_cols = missing_summary[
    missing_summary["missing_percent"] > threshold
].index.tolist()


# --------------------------------------------------
# 4. CREATE A WORKING VIEW
# --------------------------------------------------

# This DataFrame hides the high-missing columns
df_working = df_clean.drop(columns=high_missing_cols)


# --------------------------------------------------
# 5. SUMMARY
# --------------------------------------------------

print("Original df1 shape:", df1.shape)
print("Cleaned df shape:", df_clean.shape)
print("Working df shape:", df_working.shape)

print(
    f"\nColumns hidden because they are > {threshold}% missing:",
    len(high_missing_cols)
)

print("\nTop missing columns:")
display(missing_summary.head(20))

Original df1 shape: (4464, 799)
Cleaned df shape: (4464, 799)
Working df shape: (4464, 788)

Columns hidden because they are > 80% missing: 9

Top missing columns:

                                    missing_count  missing_percent
w_t_g169_real_power_a_c                      3821        85.595878
w_t_g169_blade_setpoint_position_1           3704        82.974910
w_t_g169_blade_setpoint_position_3           3704        82.974910
w_t_g169_blade_setpoint_position_2           3704        82.974910
w_t_g169_blade_position_3                    3702        82.930108
w_t_g169_blade_position_1                    3701        82.907706
w_t_g169_blade_position_2                    3701        82.907706
w_t_g169_nacelle_position                    3634        81.406810
w_t_g194_real_power_a_c                      3596        80.555556
w_t_g169_temperature_ambient                 3485        78.068996
w_t_g154_real_power_a_c                      3484        78.046595
w_t_g169_wind_speed                          3483        78.024194
w_t_g169_real_power_a_c                      3482        78.001792
w_t_g169_wind_direction                      3480        77.956989
w_t_g169_wind_speed                          3480        77.956989
w_t_g169_wind_direction_relative             3480        77.956989
w_t_g155_real_power_a_c                      3315        74.260753
w_t_g194_blade_setpoint_position_3           3066        68.682796
w_t_g171_real_power_a_c                      3064        68.637993
w_t_g194_blade_setpoint_position_2           3059        68.525986

In [28]:
for col in df_clean.columns:
    print(col)

utc_time
w_t_g150_air_density
w_t_g150_temperature_ambient_merged
w_t_g150_real_power_a_c
w_t_g150_theoretical_power
w_t_g150_wind_speed
w_t_g150_temperature_ambient
w_t_g150_real_power_a_c
w_t_g150_nacelle_position
w_t_g150_blade_position_2
w_t_g150_blade_position_3
w_t_g150_blade_setpoint_position_1
w_t_g150_blade_setpoint_position_2
w_t_g150_blade_setpoint_position_3
w_t_g150_wind_speed
w_t_g150_wind_direction
w_t_g150_wind_direction_relative
w_t_g151_air_density
w_t_g151_temperature_ambient_merged
w_t_g151_real_power_a_c
w_t_g151_theoretical_power
w_t_g151_wind_speed
w_t_g151_temperature_ambient
w_t_g151_real_power_a_c
w_t_g151_nacelle_position
w_t_g151_blade_position_1
w_t_g151_blade_position_2
w_t_g151_blade_position_3
w_t_g151_blade_setpoint_position_1
w_t_g151_blade_setpoint_position_2
w_t_g151_blade_setpoint_position_3
w_t_g151_wind_speed
w_t_g151_wind_direction
w_t_g151_wind_direction_relative
w_t_g152_air_density
w_t_g152_temperature_ambient_merged
w_t_g152_real_power_a_c
w_t_g152_theoretical_power
w_t_g152_wind_speed
w_t_g152_temperature_ambient
w_t_g152_real_power_a_c
w_t_g152_nacelle_position
w_t_g152_blade_position_1
w_t_g152_blade_position_2
w_t_g152_blade_position_3
w_t_g152_blade_setpoint_position_1
w_t_g152_blade_setpoint_position_2
w_t_g152_blade_setpoint_position_3
w_t_g152_wind_speed
w_t_g152_wind_direction
w_t_g152_wind_direction_relative
w_t_g153_air_density
w_t_g153_temperature_ambient_merged
w_t_g153_real_power_a_c
w_t_g153_theoretical_power
w_t_g153_wind_speed
w_t_g153_temperature_ambient
w_t_g153_real_power_a_c
w_t_g153_nacelle_position
w_t_g153_blade_position_1
w_t_g153_blade_position_2
w_t_g153_blade_position_3
w_t_g153_blade_setpoint_position_1
w_t_g153_blade_setpoint_position_2
w_t_g153_blade_setpoint_position_3
w_t_g153_wind_speed
w_t_g153_wind_direction
w_t_g153_wind_direction_relative
w_t_g154_air_density
w_t_g154_temperature_ambient_merged
w_t_g154_real_power_a_c
w_t_g154_theoretical_power
w_t_g154_wind_speed
w_t_g154_temperature_ambient
w_t_g154_real_power_a_c
w_t_g154_nacelle_position
w_t_g154_blade_position_1
w_t_g154_blade_position_2
w_t_g154_blade_position_3
w_t_g154_blade_setpoint_position_1
w_t_g154_blade_setpoint_position_2
w_t_g154_blade_setpoint_position_3
w_t_g154_wind_speed
w_t_g154_wind_direction
w_t_g154_wind_direction_relative
w_t_g155_air_density
w_t_g155_temperature_ambient_merged
w_t_g155_real_power_a_c
w_t_g155_theoretical_power
w_t_g155_wind_speed
w_t_g155_temperature_ambient
w_t_g155_real_power_a_c
w_t_g155_nacelle_position
w_t_g155_blade_position_1
w_t_g155_blade_position_2
w_t_g155_blade_position_3
w_t_g155_blade_setpoint_position_1
w_t_g155_blade_setpoint_position_2
w_t_g155_blade_setpoint_position_3
w_t_g155_wind_speed
w_t_g155_wind_direction
w_t_g155_wind_direction_relative
w_t_g156_air_density
w_t_g156_temperature_ambient_merged
w_t_g156_real_power_a_c
w_t_g156_theoretical_power
w_t_g156_wind_speed
w_t_g156_temperature_ambient
w_t_g156_real_power_a_c
w_t_g156_nacelle_position
w_t_g156_blade_position_1
w_t_g156_blade_position_2
w_t_g156_blade_position_3
w_t_g156_blade_setpoint_position_1
w_t_g156_blade_setpoint_position_2
w_t_g156_blade_setpoint_position_3
w_t_g156_wind_speed
w_t_g156_wind_direction
w_t_g156_wind_direction_relative
w_t_g157_air_density
w_t_g157_temperature_ambient_merged
w_t_g157_real_power_a_c
w_t_g157_theoretical_power
w_t_g157_wind_speed
w_t_g157_temperature_ambient
w_t_g157_real_power_a_c
w_t_g157_nacelle_position
w_t_g157_blade_position_1
w_t_g157_blade_position_2
w_t_g157_blade_position_3
w_t_g157_blade_setpoint_position_1
w_t_g157_blade_setpoint_position_2
w_t_g157_blade_setpoint_position_3
w_t_g157_wind_speed
w_t_g157_wind_direction
w_t_g157_wind_direction_relative
w_t_g158_air_density
w_t_g158_temperature_ambient_merged
w_t_g158_real_power_a_c
w_t_g158_theoretical_power
w_t_g158_wind_speed
w_t_g158_temperature_ambient
w_t_g158_real_power_a_c
w_t_g158_nacelle_position
w_t_g158_blade_position_1
w_t_g158_blade_position_2
w_t_g158_blade_position_3
w_t_g158_blade_setpoint_position_1
w_t_g158_blade_setpoint_position_2
w_t_g158_blade_setpoint_position_3
w_t_g158_wind_speed
w_t_g158_wind_direction
w_t_g158_wind_direction_relative
w_t_g159_air_density
w_t_g159_temperature_ambient_merged
w_t_g159_real_power_a_c
w_t_g159_theoretical_power
w_t_g159_wind_speed
w_t_g159_temperature_ambient
w_t_g159_real_power_a_c
w_t_g159_nacelle_position
w_t_g159_blade_position_1
w_t_g159_blade_position_2
w_t_g159_blade_position_3
w_t_g159_blade_setpoint_position_1
w_t_g159_blade_setpoint_position_2
w_t_g159_blade_setpoint_position_3
w_t_g159_wind_speed
w_t_g159_wind_direction
w_t_g159_wind_direction_relative
w_t_g161_air_density
w_t_g161_temperature_ambient_merged
w_t_g161_real_power_a_c
w_t_g161_theoretical_power
w_t_g161_wind_speed
w_t_g161_temperature_ambient
w_t_g161_real_power_a_c
w_t_g161_nacelle_position
w_t_g161_blade_position_1
w_t_g161_blade_position_2
w_t_g161_blade_position_3
w_t_g161_blade_setpoint_position_1
w_t_g161_blade_setpoint_position_2
w_t_g161_blade_setpoint_position_3
w_t_g161_wind_speed
w_t_g161_wind_direction
w_t_g161_wind_direction_relative
w_t_g162_air_density
w_t_g162_temperature_ambient_merged
w_t_g162_real_power_a_c
w_t_g162_theoretical_power
w_t_g162_wind_speed
w_t_g162_temperature_ambient
w_t_g162_real_power_a_c
w_t_g162_nacelle_position
w_t_g162_blade_position_1
w_t_g162_blade_position_2
w_t_g162_blade_position_3
w_t_g162_blade_setpoint_position_1
w_t_g162_blade_setpoint_position_2
w_t_g162_blade_setpoint_position_3
w_t_g162_wind_speed
w_t_g162_wind_direction
w_t_g162_wind_direction_relative
w_t_g163_air_density
w_t_g163_temperature_ambient_merged
w_t_g163_real_power_a_c
w_t_g163_theoretical_power
w_t_g163_wind_speed
w_t_g163_temperature_ambient
w_t_g163_real_power_a_c
w_t_g163_nacelle_position
w_t_g163_blade_position_1
w_t_g163_blade_position_2
w_t_g163_blade_position_3
w_t_g163_blade_setpoint_position_1
w_t_g163_blade_setpoint_position_2
w_t_g163_blade_setpoint_position_3
w_t_g163_wind_speed
w_t_g163_wind_direction
w_t_g163_wind_direction_relative
w_t_g164_air_density
w_t_g164_temperature_ambient_merged
w_t_g164_real_power_a_c
w_t_g164_theoretical_power
w_t_g164_wind_speed
w_t_g164_temperature_ambient
w_t_g164_real_power_a_c
w_t_g164_nacelle_position
w_t_g164_blade_position_1
w_t_g164_blade_position_2
w_t_g164_blade_position_3
w_t_g164_blade_setpoint_position_1
w_t_g164_blade_setpoint_position_2
w_t_g164_blade_setpoint_position_3
w_t_g164_wind_speed
w_t_g164_wind_direction
w_t_g164_wind_direction_relative
w_t_g165_air_density
w_t_g165_temperature_ambient_merged
w_t_g165_real_power_a_c
w_t_g165_theoretical_power
w_t_g165_wind_speed
w_t_g165_temperature_ambient
w_t_g165_real_power_a_c
w_t_g165_nacelle_position
w_t_g165_blade_position_1
w_t_g165_blade_position_2
w_t_g165_blade_position_3
w_t_g165_blade_setpoint_position_1
w_t_g165_blade_setpoint_position_2
w_t_g165_blade_setpoint_position_3
w_t_g165_wind_speed
w_t_g165_wind_direction
w_t_g165_wind_direction_relative
w_t_g166_air_density
w_t_g166_temperature_ambient_merged
w_t_g166_real_power_a_c
w_t_g166_theoretical_power
w_t_g166_wind_speed
w_t_g166_temperature_ambient
w_t_g166_real_power_a_c
w_t_g166_nacelle_position
w_t_g166_blade_position_1
w_t_g166_blade_position_2
w_t_g166_blade_position_3
w_t_g166_blade_setpoint_position_1
w_t_g166_blade_setpoint_position_2
w_t_g166_blade_setpoint_position_3
w_t_g166_wind_speed
w_t_g166_wind_direction
w_t_g166_wind_direction_relative
w_t_g167_air_density
w_t_g167_temperature_ambient_merged
w_t_g167_real_power_a_c
w_t_g167_theoretical_power
w_t_g167_wind_speed
w_t_g167_temperature_ambient
w_t_g167_real_power_a_c
w_t_g167_nacelle_position
w_t_g167_blade_position_1
w_t_g167_blade_position_2
w_t_g167_blade_position_3
w_t_g167_blade_setpoint_position_1
w_t_g167_blade_setpoint_position_2
w_t_g167_blade_setpoint_position_3
w_t_g167_wind_speed
w_t_g167_wind_direction
w_t_g167_wind_direction_relative
w_t_g168_air_density
w_t_g168_temperature_ambient_merged
w_t_g168_real_power_a_c
w_t_g168_theoretical_power
w_t_g168_wind_speed
w_t_g168_temperature_ambient
w_t_g168_real_power_a_c
w_t_g168_nacelle_position
w_t_g168_blade_position_1
w_t_g168_blade_position_2
w_t_g168_blade_position_3
w_t_g168_blade_setpoint_position_1
w_t_g168_blade_setpoint_position_2
w_t_g168_blade_setpoint_position_3
w_t_g168_wind_speed
w_t_g168_wind_direction
w_t_g168_wind_direction_relative
w_t_g169_air_density
w_t_g169_temperature_ambient_merged
w_t_g169_real_power_a_c
w_t_g169_theoretical_power
w_t_g169_wind_speed
w_t_g169_temperature_ambient
w_t_g169_real_power_a_c
w_t_g169_nacelle_position
w_t_g169_blade_position_1
w_t_g169_blade_position_2
w_t_g169_blade_position_3
w_t_g169_blade_setpoint_position_1
w_t_g169_blade_setpoint_position_2
w_t_g169_blade_setpoint_position_3
w_t_g169_wind_speed
w_t_g169_wind_direction
w_t_g169_wind_direction_relative
w_t_g170_air_density
w_t_g170_temperature_ambient_merged
w_t_g170_real_power_a_c
w_t_g170_theoretical_power
w_t_g170_wind_speed
w_t_g170_temperature_ambient
w_t_g170_real_power_a_c
w_t_g170_nacelle_position
w_t_g170_blade_position_1
w_t_g170_blade_position_2
w_t_g170_blade_position_3
w_t_g170_blade_setpoint_position_1
w_t_g170_blade_setpoint_position_2
w_t_g170_blade_setpoint_position_3
w_t_g170_wind_speed
w_t_g170_wind_direction
w_t_g170_wind_direction_relative
w_t_g171_air_density
w_t_g171_temperature_ambient_merged
w_t_g171_real_power_a_c
w_t_g171_theoretical_power
w_t_g171_wind_speed
w_t_g171_temperature_ambient
w_t_g171_real_power_a_c
w_t_g171_nacelle_position
w_t_g171_blade_position_1
w_t_g171_blade_position_2
w_t_g171_blade_position_3
w_t_g171_blade_setpoint_position_1
w_t_g171_blade_setpoint_position_2
w_t_g171_blade_setpoint_position_3
w_t_g171_wind_speed
w_t_g171_wind_direction
w_t_g171_wind_direction_relative
w_t_g172_air_density
w_t_g172_temperature_ambient_merged
w_t_g172_real_power_a_c
w_t_g172_theoretical_power
w_t_g172_wind_speed
w_t_g172_temperature_ambient
w_t_g172_real_power_a_c
w_t_g172_nacelle_position
w_t_g172_blade_position_1
w_t_g172_blade_position_2
w_t_g172_blade_position_3
w_t_g172_blade_setpoint_position_1
w_t_g172_blade_setpoint_position_2
w_t_g172_blade_setpoint_position_3
w_t_g172_wind_speed
w_t_g172_wind_direction
w_t_g172_wind_direction_relative
w_t_g173_air_density
w_t_g173_temperature_ambient_merged
w_t_g173_real_power_a_c
w_t_g173_theoretical_power
w_t_g173_wind_speed
w_t_g173_temperature_ambient
w_t_g173_real_power_a_c
w_t_g173_nacelle_position
w_t_g173_blade_position_1
w_t_g173_blade_position_2
w_t_g173_blade_position_3
w_t_g173_blade_setpoint_position_1
w_t_g173_blade_setpoint_position_2
w_t_g173_blade_setpoint_position_3
w_t_g173_wind_speed
w_t_g173_wind_direction
w_t_g173_wind_direction_relative
w_t_g174_air_density
w_t_g174_temperature_ambient_merged
w_t_g174_real_power_a_c
w_t_g174_theoretical_power
w_t_g174_wind_speed
w_t_g174_temperature_ambient
w_t_g174_real_power_a_c
w_t_g174_nacelle_position
w_t_g174_blade_position_1
w_t_g174_blade_position_2
w_t_g174_blade_position_3
w_t_g174_blade_setpoint_position_1
w_t_g174_blade_setpoint_position_2
w_t_g174_blade_setpoint_position_3
w_t_g174_wind_speed
w_t_g174_wind_direction
w_t_g174_wind_direction_relative
w_t_g175_air_density
w_t_g175_temperature_ambient_merged
w_t_g175_real_power_a_c
w_t_g175_theoretical_power
w_t_g175_wind_speed
w_t_g175_temperature_ambient
w_t_g175_real_power_a_c
w_t_g175_nacelle_position
w_t_g175_blade_position_1
w_t_g175_blade_position_2
w_t_g175_blade_position_3
w_t_g175_blade_setpoint_position_1
w_t_g175_blade_setpoint_position_2
w_t_g175_blade_setpoint_position_3
w_t_g175_wind_speed
w_t_g175_wind_direction
w_t_g175_wind_direction_relative
w_t_g176_air_density
w_t_g176_temperature_ambient_merged
w_t_g176_real_power_a_c
w_t_g176_theoretical_power
w_t_g176_wind_speed
w_t_g176_temperature_ambient
w_t_g176_real_power_a_c
w_t_g176_nacelle_position
w_t_g176_blade_position_1
w_t_g176_blade_position_2
w_t_g176_blade_position_3
w_t_g176_blade_setpoint_position_1
w_t_g176_blade_setpoint_position_2
w_t_g176_blade_setpoint_position_3
w_t_g176_wind_speed
w_t_g176_wind_direction
w_t_g176_wind_direction_relative
w_t_g177_air_density
w_t_g177_temperature_ambient_merged
w_t_g177_real_power_a_c
w_t_g177_theoretical_power
w_t_g177_wind_speed
w_t_g177_temperature_ambient
w_t_g177_real_power_a_c
w_t_g177_nacelle_position
w_t_g177_blade_position_1
w_t_g177_blade_position_2
w_t_g177_blade_position_3
w_t_g177_blade_setpoint_position_1
w_t_g177_blade_setpoint_position_2
w_t_g177_blade_setpoint_position_3
w_t_g177_wind_speed
w_t_g177_wind_direction
w_t_g177_wind_direction_relative
w_t_g178_air_density
w_t_g178_temperature_ambient_merged
w_t_g178_real_power_a_c
w_t_g178_theoretical_power
w_t_g178_wind_speed
w_t_g178_temperature_ambient
w_t_g178_real_power_a_c
w_t_g178_nacelle_position
w_t_g178_blade_position_1
w_t_g178_blade_position_2
w_t_g178_blade_position_3
w_t_g178_blade_setpoint_position_1
w_t_g178_blade_setpoint_position_2
w_t_g178_blade_setpoint_position_3
w_t_g178_wind_speed
w_t_g178_wind_direction
w_t_g178_wind_direction_relative
w_t_g179_air_density
w_t_g179_temperature_ambient_merged
w_t_g179_real_power_a_c
w_t_g179_theoretical_power
w_t_g179_wind_speed
w_t_g179_temperature_ambient
w_t_g179_real_power_a_c
w_t_g179_nacelle_position
w_t_g179_blade_position_1
w_t_g179_blade_position_2
w_t_g179_blade_position_3
w_t_g179_blade_setpoint_position_1
w_t_g179_blade_setpoint_position_2
w_t_g179_blade_setpoint_position_3
w_t_g179_wind_speed
w_t_g179_wind_direction
w_t_g179_wind_direction_relative
w_t_g180_air_density
w_t_g180_temperature_ambient_merged
w_t_g180_real_power_a_c
w_t_g180_theoretical_power
w_t_g180_wind_speed
w_t_g180_temperature_ambient
w_t_g180_real_power_a_c
w_t_g180_nacelle_position
w_t_g180_blade_position_1
w_t_g180_blade_position_2
w_t_g180_blade_position_3
w_t_g180_blade_setpoint_position_1
w_t_g180_blade_setpoint_position_2
w_t_g180_blade_setpoint_position_3
w_t_g180_wind_speed
w_t_g180_wind_direction
w_t_g180_wind_direction_relative
w_t_g181_air_density
w_t_g181_temperature_ambient_merged
w_t_g181_real_power_a_c
w_t_g181_theoretical_power
w_t_g181_wind_speed
w_t_g181_temperature_ambient
w_t_g181_real_power_a_c
w_t_g181_nacelle_position
w_t_g181_blade_position_1
w_t_g181_blade_position_2
w_t_g181_blade_position_3
w_t_g181_blade_setpoint_position_1
w_t_g181_blade_setpoint_position_2
w_t_g181_blade_setpoint_position_3
w_t_g181_wind_speed
w_t_g181_wind_direction
w_t_g181_wind_direction_relative
w_t_g182_air_density
w_t_g182_temperature_ambient_merged
w_t_g182_real_power_a_c
w_t_g182_theoretical_power
w_t_g182_wind_speed
w_t_g182_temperature_ambient
w_t_g182_real_power_a_c
w_t_g182_nacelle_position
w_t_g182_blade_position_1
w_t_g182_blade_position_2
w_t_g182_blade_position_3
w_t_g182_blade_setpoint_position_1
w_t_g182_blade_setpoint_position_2
w_t_g182_blade_setpoint_position_3
w_t_g182_wind_speed
w_t_g182_wind_direction
w_t_g182_wind_direction_relative
w_t_g183_air_density
w_t_g183_temperature_ambient_merged
w_t_g183_real_power_a_c
w_t_g183_theoretical_power
w_t_g183_wind_speed
w_t_g183_temperature_ambient
w_t_g183_real_power_a_c
w_t_g183_nacelle_position
w_t_g183_blade_position_1
w_t_g183_blade_position_2
w_t_g183_blade_position_3
w_t_g183_blade_setpoint_position_1
w_t_g183_blade_setpoint_position_2
w_t_g183_blade_setpoint_position_3
w_t_g183_wind_speed
w_t_g183_wind_direction
w_t_g183_wind_direction_relative
w_t_g184_air_density
w_t_g184_temperature_ambient_merged
w_t_g184_real_power_a_c
w_t_g184_theoretical_power
w_t_g184_wind_speed
w_t_g184_temperature_ambient
w_t_g184_real_power_a_c
w_t_g184_nacelle_position
w_t_g184_blade_position_1
w_t_g184_blade_position_2
w_t_g184_blade_position_3
w_t_g184_blade_setpoint_position_1
w_t_g184_blade_setpoint_position_2
w_t_g184_blade_setpoint_position_3
w_t_g184_wind_speed
w_t_g184_wind_direction
w_t_g184_wind_direction_relative
w_t_g185_air_density
w_t_g185_temperature_ambient_merged
w_t_g185_real_power_a_c
w_t_g185_theoretical_power
w_t_g185_wind_speed
w_t_g185_temperature_ambient
w_t_g185_real_power_a_c
w_t_g185_nacelle_position
w_t_g185_blade_position_1
w_t_g185_blade_position_2
w_t_g185_blade_position_3
w_t_g185_blade_setpoint_position_1
w_t_g185_blade_setpoint_position_2
w_t_g185_blade_setpoint_position_3
w_t_g185_wind_speed
w_t_g185_wind_direction
w_t_g185_wind_direction_relative
w_t_g186_air_density
w_t_g186_temperature_ambient_merged
w_t_g186_real_power_a_c
w_t_g186_theoretical_power
w_t_g186_wind_speed
w_t_g186_temperature_ambient
w_t_g186_real_power_a_c
w_t_g186_nacelle_position
w_t_g186_blade_position_1
w_t_g186_blade_position_2
w_t_g186_blade_position_3
w_t_g186_blade_setpoint_position_1
w_t_g186_blade_setpoint_position_2
w_t_g186_blade_setpoint_position_3
w_t_g186_wind_speed
w_t_g186_wind_direction
w_t_g186_wind_direction_relative
w_t_g187_air_density
w_t_g187_temperature_ambient_merged
w_t_g187_real_power_a_c
w_t_g187_theoretical_power
w_t_g187_wind_speed
w_t_g187_temperature_ambient
w_t_g187_real_power_a_c
w_t_g187_nacelle_position
w_t_g187_blade_position_1
w_t_g187_blade_position_2
w_t_g187_blade_position_3
w_t_g187_blade_setpoint_position_1
w_t_g187_blade_setpoint_position_2
w_t_g187_blade_setpoint_position_3
w_t_g187_wind_speed
w_t_g187_wind_direction
w_t_g187_wind_direction_relative
w_t_g188_air_density
w_t_g188_temperature_ambient_merged
w_t_g188_real_power_a_c
w_t_g188_theoretical_power
w_t_g188_wind_speed
w_t_g188_temperature_ambient
w_t_g188_real_power_a_c
w_t_g188_nacelle_position
w_t_g188_blade_position_1
w_t_g188_blade_position_2
w_t_g188_blade_position_3
w_t_g188_blade_setpoint_position_1
w_t_g188_blade_setpoint_position_2
w_t_g188_blade_setpoint_position_3
w_t_g188_wind_speed
w_t_g188_wind_direction
w_t_g188_wind_direction_relative
w_t_g189_air_density
w_t_g189_temperature_ambient_merged
w_t_g189_real_power_a_c
w_t_g189_theoretical_power
w_t_g189_wind_speed
w_t_g189_temperature_ambient
w_t_g189_real_power_a_c
w_t_g189_nacelle_position
w_t_g189_blade_position_1
w_t_g189_blade_position_2
w_t_g189_blade_position_3
w_t_g189_blade_setpoint_position_1
w_t_g189_blade_setpoint_position_2
w_t_g189_blade_setpoint_position_3
w_t_g189_wind_speed
w_t_g189_wind_direction
w_t_g189_wind_direction_relative
w_t_g190_air_density
w_t_g190_temperature_ambient_merged
w_t_g190_real_power_a_c
w_t_g190_theoretical_power
w_t_g190_wind_speed
w_t_g190_temperature_ambient
w_t_g190_real_power_a_c
w_t_g190_nacelle_position
w_t_g190_blade_position_1
w_t_g190_blade_position_2
w_t_g190_blade_position_3
w_t_g190_blade_setpoint_position_1
w_t_g190_blade_setpoint_position_2
w_t_g190_blade_setpoint_position_3
w_t_g190_wind_speed
w_t_g190_wind_direction
w_t_g190_wind_direction_relative
w_t_g191_air_density
w_t_g191_temperature_ambient_merged
w_t_g191_real_power_a_c
w_t_g191_theoretical_power
w_t_g191_wind_speed
w_t_g191_temperature_ambient
w_t_g191_real_power_a_c
w_t_g191_nacelle_position
w_t_g191_blade_position_1
w_t_g191_blade_position_2
w_t_g191_blade_position_3
w_t_g191_blade_setpoint_position_1
w_t_g191_blade_setpoint_position_2
w_t_g191_blade_setpoint_position_3
w_t_g191_wind_speed
w_t_g191_wind_direction
w_t_g191_wind_direction_relative
w_t_g192_air_density
w_t_g192_temperature_ambient_merged
w_t_g192_real_power_a_c
w_t_g192_theoretical_power
w_t_g192_wind_speed
w_t_g192_temperature_ambient
w_t_g192_real_power_a_c
w_t_g192_nacelle_position
w_t_g192_blade_position_1
w_t_g192_blade_position_2
w_t_g192_blade_position_3
w_t_g192_blade_setpoint_position_1
w_t_g192_blade_setpoint_position_2
w_t_g192_blade_setpoint_position_3
w_t_g192_wind_speed
w_t_g192_wind_direction
w_t_g192_wind_direction_relative
w_t_g193_air_density
w_t_g193_temperature_ambient_merged
w_t_g193_real_power_a_c
w_t_g193_theoretical_power
w_t_g193_wind_speed
w_t_g193_temperature_ambient
w_t_g193_real_power_a_c
w_t_g193_nacelle_position
w_t_g193_blade_position_1
w_t_g193_blade_position_2
w_t_g193_blade_position_3
w_t_g193_blade_setpoint_position_1
w_t_g193_blade_setpoint_position_2
w_t_g193_blade_setpoint_position_3

In [31]:
print("Duplicate column names:", df_clean.columns.duplicated().sum())

duplicates = df_clean.columns[df_clean.columns.duplicated()].tolist()
print(duplicates)

Duplicate column names: 94
['w_t_g150_real_power_a_c', 'w_t_g150_wind_speed', 'w_t_g151_real_power_a_c', 'w_t_g151_wind_speed', 'w_t_g152_real_power_a_c', 'w_t_g152_wind_speed', 'w_t_g153_real_power_a_c', 'w_t_g153_wind_speed', 'w_t_g154_real_power_a_c', 'w_t_g154_wind_speed', 'w_t_g155_real_power_a_c', 'w_t_g155_wind_speed', 'w_t_g156_real_power_a_c', 'w_t_g156_wind_speed', 'w_t_g157_real_power_a_c', 'w_t_g157_wind_speed', 'w_t_g158_real_power_a_c', 'w_t_g158_wind_speed', 'w_t_g159_real_power_a_c', 'w_t_g159_wind_speed', 'w_t_g161_real_power_a_c', 'w_t_g161_wind_speed', 'w_t_g162_real_power_a_c', 'w_t_g162_wind_speed', 'w_t_g163_real_power_a_c', 'w_t_g163_wind_speed', 'w_t_g164_real_power_a_c', 'w_t_g164_wind_speed', 'w_t_g165_real_power_a_c', 'w_t_g165_wind_speed', 'w_t_g166_real_power_a_c', 'w_t_g166_wind_speed', 'w_t_g167_real_power_a_c', 'w_t_g167_wind_speed', 'w_t_g168_real_power_a_c', 'w_t_g168_wind_speed', 'w_t_g169_real_power_a_c', 'w_t_g169_wind_speed', 'w_t_g170_real_power_a_c', 'w_t_g170_wind_speed', 'w_t_g171_real_power_a_c', 'w_t_g171_wind_speed', 'w_t_g172_real_power_a_c', 'w_t_g172_wind_speed', 'w_t_g173_real_power_a_c', 'w_t_g173_wind_speed', 'w_t_g174_real_power_a_c', 'w_t_g174_wind_speed', 'w_t_g175_real_power_a_c', 'w_t_g175_wind_speed', 'w_t_g176_real_power_a_c', 'w_t_g176_wind_speed', 'w_t_g177_real_power_a_c', 'w_t_g177_wind_speed', 'w_t_g178_real_power_a_c', 'w_t_g178_wind_speed', 'w_t_g179_real_power_a_c', 'w_t_g179_wind_speed', 'w_t_g180_real_power_a_c', 'w_t_g180_wind_speed', 'w_t_g181_real_power_a_c', 'w_t_g181_wind_speed', 'w_t_g182_real_power_a_c', 'w_t_g182_wind_speed', 'w_t_g183_real_power_a_c', 'w_t_g183_wind_speed', 'w_t_g184_real_power_a_c', 'w_t_g184_wind_speed', 'w_t_g185_real_power_a_c', 'w_t_g185_wind_speed', 'w_t_g186_real_power_a_c', 'w_t_g186_wind_speed', 'w_t_g187_real_power_a_c', 'w_t_g187_wind_speed', 'w_t_g188_real_power_a_c', 'w_t_g188_wind_speed', 'w_t_g189_real_power_a_c', 'w_t_g189_wind_speed', 'w_t_g190_real_power_a_c', 'w_t_g190_wind_speed', 'w_t_g191_real_power_a_c', 'w_t_g191_wind_speed', 'w_t_g192_real_power_a_c', 'w_t_g192_wind_speed', 'w_t_g193_real_power_a_c', 'w_t_g193_wind_speed', 'w_t_g194_real_power_a_c', 'w_t_g194_wind_speed', 'w_t_g195_real_power_a_c', 'w_t_g195_wind_speed', 'w_t_g196_real_power_a_c', 'w_t_g196_wind_speed', 'w_t_g197_real_power_a_c', 'w_t_g197_wind_speed']

In [32]:
import pandas as pd
import re

rows = []

for i, col in enumerate(df_clean.columns):

    if col == "utc_time":
        continue

    # Works with names like w_t_g169_real_power_a_c
    match = re.match(r"(w_t_g\d+)_(.+)", str(col))

    if match:
        turbine = match.group(1)
        variable = match.group(2)

        # Access by column POSITION so duplicate names aren't a problem
        column_data = df_clean.iloc[:, i]

        rows.append({
            "turbine": turbine,
            "variable": variable,
            "column_name": col,
            "column_position": i,
            "missing_count": column_data.isna().sum(),
            "missing_percent": column_data.isna().mean() * 100
        })

missing_by_turbine = pd.DataFrame(rows)

missing_by_turbine = (
    missing_by_turbine
    .sort_values(
        ["turbine", "missing_percent"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

missing_by_turbine

,turbine,variable,column_name,column_position,missing_count,missing_percent
0,w_t_g150,real_power_a_c,w_t_g150_real_power_a_c,7,2689,60.237455
1,w_t_g150,blade_setpoint_position_1,w_t_g150_blade_setpoint_position_1,11,2096,46.953405
2,w_t_g150,blade_setpoint_position_2,w_t_g150_blade_setpoint_position_2,12,2096,46.953405
3,w_t_g150,blade_setpoint_position_3,w_t_g150_blade_setpoint_position_3,13,2096,46.953405
4,w_t_g150,blade_position_2,w_t_g150_blade_position_2,9,2027,45.407706
...,...,...,...,...,...,...
793,w_t_g197,wind_direction,w_t_g197_wind_direction,797,1,0.022401
794,w_t_g197,wind_direction_relative,w_t_g197_wind_direction_relative,798,1,0.022401
795,w_t_g197,air_density,w_t_g197_air_density,782,0,0.000000
796,w_t_g197,temperature_ambient_merged,w_t_g197_temperature_ambient_merged,783,0,0.000000
797,w_t_g197,theoretical_power,w_t_g197_theoretical_power,785,0,0.000000

In [34]:
import pandas as pd
from collections import Counter

# --------------------------------------------------
# MAKE DUPLICATE COLUMN NAMES UNIQUE
# --------------------------------------------------

counts = Counter()
unique_columns = []

for col in df_clean.columns:
    counts[col] += 1

    if counts[col] == 1:
        unique_columns.append(col)
    else:
        unique_columns.append(f"{col}_{counts[col]}")

df_clean.columns = unique_columns


# --------------------------------------------------
# CHECK FOR DUPLICATES
# --------------------------------------------------

print(
    "Duplicate column names:",
    df_clean.columns.duplicated().sum()
)

# Optional: see the final column names
for col in df_clean.columns:
    print(col)

Duplicate column names: 0
utc_time
w_t_g150_air_density
w_t_g150_temperature_ambient_merged
w_t_g150_real_power_a_c
w_t_g150_theoretical_power
w_t_g150_wind_speed
w_t_g150_temperature_ambient
w_t_g150_real_power_a_c_2
w_t_g150_nacelle_position
w_t_g150_blade_position_2
w_t_g150_blade_position_3
w_t_g150_blade_setpoint_position_1
w_t_g150_blade_setpoint_position_2
w_t_g150_blade_setpoint_position_3
w_t_g150_wind_speed_2
w_t_g150_wind_direction
w_t_g150_wind_direction_relative
w_t_g151_air_density
w_t_g151_temperature_ambient_merged
w_t_g151_real_power_a_c
w_t_g151_theoretical_power
w_t_g151_wind_speed
w_t_g151_temperature_ambient
w_t_g151_real_power_a_c_2
w_t_g151_nacelle_position
w_t_g151_blade_position_1
w_t_g151_blade_position_2
w_t_g151_blade_position_3
w_t_g151_blade_setpoint_position_1
w_t_g151_blade_setpoint_position_2
w_t_g151_blade_setpoint_position_3
w_t_g151_wind_speed_2
w_t_g151_wind_direction
w_t_g151_wind_direction_relative
w_t_g152_air_density
w_t_g152_temperature_ambient_merged
w_t_g152_real_power_a_c
w_t_g152_theoretical_power
w_t_g152_wind_speed
w_t_g152_temperature_ambient
w_t_g152_real_power_a_c_2
w_t_g152_nacelle_position
w_t_g152_blade_position_1
w_t_g152_blade_position_2
w_t_g152_blade_position_3
w_t_g152_blade_setpoint_position_1
w_t_g152_blade_setpoint_position_2
w_t_g152_blade_setpoint_position_3
w_t_g152_wind_speed_2
w_t_g152_wind_direction
w_t_g152_wind_direction_relative
w_t_g153_air_density
w_t_g153_temperature_ambient_merged
w_t_g153_real_power_a_c
w_t_g153_theoretical_power
w_t_g153_wind_speed
w_t_g153_temperature_ambient
w_t_g153_real_power_a_c_2
w_t_g153_nacelle_position
w_t_g153_blade_position_1
w_t_g153_blade_position_2
w_t_g153_blade_position_3
w_t_g153_blade_setpoint_position_1
w_t_g153_blade_setpoint_position_2
w_t_g153_blade_setpoint_position_3
w_t_g153_wind_speed_2
w_t_g153_wind_direction
w_t_g153_wind_direction_relative
w_t_g154_air_density
w_t_g154_temperature_ambient_merged
w_t_g154_real_power_a_c
w_t_g154_theoretical_power
w_t_g154_wind_speed
w_t_g154_temperature_ambient
w_t_g154_real_power_a_c_2
w_t_g154_nacelle_position
w_t_g154_blade_position_1
w_t_g154_blade_position_2
w_t_g154_blade_position_3
w_t_g154_blade_setpoint_position_1
w_t_g154_blade_setpoint_position_2
w_t_g154_blade_setpoint_position_3
w_t_g154_wind_speed_2
w_t_g154_wind_direction
w_t_g154_wind_direction_relative
w_t_g155_air_density
w_t_g155_temperature_ambient_merged
w_t_g155_real_power_a_c
w_t_g155_theoretical_power
w_t_g155_wind_speed
w_t_g155_temperature_ambient
w_t_g155_real_power_a_c_2
w_t_g155_nacelle_position
w_t_g155_blade_position_1
w_t_g155_blade_position_2
w_t_g155_blade_position_3
w_t_g155_blade_setpoint_position_1
w_t_g155_blade_setpoint_position_2
w_t_g155_blade_setpoint_position_3
w_t_g155_wind_speed_2
w_t_g155_wind_direction
w_t_g155_wind_direction_relative
w_t_g156_air_density
w_t_g156_temperature_ambient_merged
w_t_g156_real_power_a_c
w_t_g156_theoretical_power
w_t_g156_wind_speed
w_t_g156_temperature_ambient
w_t_g156_real_power_a_c_2
w_t_g156_nacelle_position
w_t_g156_blade_position_1
w_t_g156_blade_position_2
w_t_g156_blade_position_3
w_t_g156_blade_setpoint_position_1
w_t_g156_blade_setpoint_position_2
w_t_g156_blade_setpoint_position_3
w_t_g156_wind_speed_2
w_t_g156_wind_direction
w_t_g156_wind_direction_relative
w_t_g157_air_density
w_t_g157_temperature_ambient_merged
w_t_g157_real_power_a_c
w_t_g157_theoretical_power
w_t_g157_wind_speed
w_t_g157_temperature_ambient
w_t_g157_real_power_a_c_2
w_t_g157_nacelle_position
w_t_g157_blade_position_1
w_t_g157_blade_position_2
w_t_g157_blade_position_3
w_t_g157_blade_setpoint_position_1
w_t_g157_blade_setpoint_position_2
w_t_g157_blade_setpoint_position_3
w_t_g157_wind_speed_2
w_t_g157_wind_direction
w_t_g157_wind_direction_relative
w_t_g158_air_density
w_t_g158_temperature_ambient_merged
w_t_g158_real_power_a_c
w_t_g158_theoretical_power
w_t_g158_wind_speed
w_t_g158_temperature_ambient
w_t_g158_real_power_a_c_2
w_t_g158_nacelle_position
w_t_g158_blade_position_1
w_t_g158_blade_position_2
w_t_g158_blade_position_3
w_t_g158_blade_setpoint_position_1
w_t_g158_blade_setpoint_position_2
w_t_g158_blade_setpoint_position_3
w_t_g158_wind_speed_2
w_t_g158_wind_direction
w_t_g158_wind_direction_relative
w_t_g159_air_density
w_t_g159_temperature_ambient_merged
w_t_g159_real_power_a_c
w_t_g159_theoretical_power
w_t_g159_wind_speed
w_t_g159_temperature_ambient
w_t_g159_real_power_a_c_2
w_t_g159_nacelle_position
w_t_g159_blade_position_1
w_t_g159_blade_position_2
w_t_g159_blade_position_3
w_t_g159_blade_setpoint_position_1
w_t_g159_blade_setpoint_position_2
w_t_g159_blade_setpoint_position_3
w_t_g159_wind_speed_2
w_t_g159_wind_direction
w_t_g159_wind_direction_relative
w_t_g161_air_density
w_t_g161_temperature_ambient_merged
w_t_g161_real_power_a_c
w_t_g161_theoretical_power
w_t_g161_wind_speed
w_t_g161_temperature_ambient
w_t_g161_real_power_a_c_2
w_t_g161_nacelle_position
w_t_g161_blade_position_1
w_t_g161_blade_position_2
w_t_g161_blade_position_3
w_t_g161_blade_setpoint_position_1
w_t_g161_blade_setpoint_position_2
w_t_g161_blade_setpoint_position_3
w_t_g161_wind_speed_2
w_t_g161_wind_direction
w_t_g161_wind_direction_relative
w_t_g162_air_density
w_t_g162_temperature_ambient_merged
w_t_g162_real_power_a_c
w_t_g162_theoretical_power
w_t_g162_wind_speed
w_t_g162_temperature_ambient
w_t_g162_real_power_a_c_2
w_t_g162_nacelle_position
w_t_g162_blade_position_1
w_t_g162_blade_position_2
w_t_g162_blade_position_3
w_t_g162_blade_setpoint_position_1
w_t_g162_blade_setpoint_position_2
w_t_g162_blade_setpoint_position_3
w_t_g162_wind_speed_2
w_t_g162_wind_direction
w_t_g162_wind_direction_relative
w_t_g163_air_density
w_t_g163_temperature_ambient_merged
w_t_g163_real_power_a_c
w_t_g163_theoretical_power
w_t_g163_wind_speed
w_t_g163_temperature_ambient
w_t_g163_real_power_a_c_2
w_t_g163_nacelle_position
w_t_g163_blade_position_1
w_t_g163_blade_position_2
w_t_g163_blade_position_3
w_t_g163_blade_setpoint_position_1
w_t_g163_blade_setpoint_position_2
w_t_g163_blade_setpoint_position_3
w_t_g163_wind_speed_2
w_t_g163_wind_direction
w_t_g163_wind_direction_relative
w_t_g164_air_density
w_t_g164_temperature_ambient_merged
w_t_g164_real_power_a_c
w_t_g164_theoretical_power
w_t_g164_wind_speed
w_t_g164_temperature_ambient
w_t_g164_real_power_a_c_2
w_t_g164_nacelle_position
w_t_g164_blade_position_1
w_t_g164_blade_position_2
w_t_g164_blade_position_3
w_t_g164_blade_setpoint_position_1
w_t_g164_blade_setpoint_position_2
w_t_g164_blade_setpoint_position_3
w_t_g164_wind_speed_2
w_t_g164_wind_direction
w_t_g164_wind_direction_relative
w_t_g165_air_density
w_t_g165_temperature_ambient_merged
w_t_g165_real_power_a_c
w_t_g165_theoretical_power
w_t_g165_wind_speed
w_t_g165_temperature_ambient
w_t_g165_real_power_a_c_2
w_t_g165_nacelle_position
w_t_g165_blade_position_1
w_t_g165_blade_position_2
w_t_g165_blade_position_3
w_t_g165_blade_setpoint_position_1
w_t_g165_blade_setpoint_position_2
w_t_g165_blade_setpoint_position_3
w_t_g165_wind_speed_2
w_t_g165_wind_direction
w_t_g165_wind_direction_relative
w_t_g166_air_density
w_t_g166_temperature_ambient_merged
w_t_g166_real_power_a_c
w_t_g166_theoretical_power
w_t_g166_wind_speed
w_t_g166_temperature_ambient
w_t_g166_real_power_a_c_2
w_t_g166_nacelle_position
w_t_g166_blade_position_1
w_t_g166_blade_position_2
w_t_g166_blade_position_3
w_t_g166_blade_setpoint_position_1
w_t_g166_blade_setpoint_position_2
w_t_g166_blade_setpoint_position_3
w_t_g166_wind_speed_2
w_t_g166_wind_direction
w_t_g166_wind_direction_relative
w_t_g167_air_density
w_t_g167_temperature_ambient_merged
w_t_g167_real_power_a_c
w_t_g167_theoretical_power
w_t_g167_wind_speed
w_t_g167_temperature_ambient
w_t_g167_real_power_a_c_2
w_t_g167_nacelle_position
w_t_g167_blade_position_1
w_t_g167_blade_position_2
w_t_g167_blade_position_3
w_t_g167_blade_setpoint_position_1
w_t_g167_blade_setpoint_position_2
w_t_g167_blade_setpoint_position_3
w_t_g167_wind_speed_2
w_t_g167_wind_direction
w_t_g167_wind_direction_relative
w_t_g168_air_density
w_t_g168_temperature_ambient_merged
w_t_g168_real_power_a_c
w_t_g168_theoretical_power
w_t_g168_wind_speed
w_t_g168_temperature_ambient
w_t_g168_real_power_a_c_2
w_t_g168_nacelle_position
w_t_g168_blade_position_1
w_t_g168_blade_position_2
w_t_g168_blade_position_3
w_t_g168_blade_setpoint_position_1
w_t_g168_blade_setpoint_position_2
w_t_g168_blade_setpoint_position_3
w_t_g168_wind_speed_2
w_t_g168_wind_direction
w_t_g168_wind_direction_relative
w_t_g169_air_density
w_t_g169_temperature_ambient_merged
w_t_g169_real_power_a_c
w_t_g169_theoretical_power
w_t_g169_wind_speed
w_t_g169_temperature_ambient
w_t_g169_real_power_a_c_2
w_t_g169_nacelle_position
w_t_g169_blade_position_1
w_t_g169_blade_position_2
w_t_g169_blade_position_3
w_t_g169_blade_setpoint_position_1
w_t_g169_blade_setpoint_position_2
w_t_g169_blade_setpoint_position_3
w_t_g169_wind_speed_2
w_t_g169_wind_direction
w_t_g169_wind_direction_relative
w_t_g170_air_density
w_t_g170_temperature_ambient_merged
w_t_g170_real_power_a_c
w_t_g170_theoretical_power
w_t_g170_wind_speed
w_t_g170_temperature_ambient
w_t_g170_real_power_a_c_2
w_t_g170_nacelle_position
w_t_g170_blade_position_1
w_t_g170_blade_position_2
w_t_g170_blade_position_3
w_t_g170_blade_setpoint_position_1
w_t_g170_blade_setpoint_position_2
w_t_g170_blade_setpoint_position_3
w_t_g170_wind_speed_2
w_t_g170_wind_direction
w_t_g170_wind_direction_relative
w_t_g171_air_density
w_t_g171_temperature_ambient_merged
w_t_g171_real_power_a_c
w_t_g171_theoretical_power
w_t_g171_wind_speed
w_t_g171_temperature_ambient
w_t_g171_real_power_a_c_2
w_t_g171_nacelle_position
w_t_g171_blade_position_1
w_t_g171_blade_position_2
w_t_g171_blade_position_3
w_t_g171_blade_setpoint_position_1
w_t_g171_blade_setpoint_position_2
w_t_g171_blade_setpoint_position_3
w_t_g171_wind_speed_2
w_t_g171_wind_direction
w_t_g171_wind_direction_relative
w_t_g172_air_density
w_t_g172_temperature_ambient_merged
w_t_g172_real_power_a_c
w_t_g172_theoretical_power
w_t_g172_wind_speed
w_t_g172_temperature_ambient
w_t_g172_real_power_a_c_2
w_t_g172_nacelle_position
w_t_g172_blade_position_1
w_t_g172_blade_position_2
w_t_g172_blade_position_3
w_t_g172_blade_setpoint_position_1
w_t_g172_blade_setpoint_position_2
w_t_g172_blade_setpoint_position_3
w_t_g172_wind_speed_2
w_t_g172_wind_direction
w_t_g172_wind_direction_relative
w_t_g173_air_density
w_t_g173_temperature_ambient_merged
w_t_g173_real_power_a_c
w_t_g173_theoretical_power
w_t_g173_wind_speed
w_t_g173_temperature_ambient
w_t_g173_real_power_a_c_2
w_t_g173_nacelle_position
w_t_g173_blade_position_1
w_t_g173_blade_position_2
w_t_g173_blade_position_3
w_t_g173_blade_setpoint_position_1
w_t_g173_blade_setpoint_position_2
w_t_g173_blade_setpoint_position_3
w_t_g173_wind_speed_2
w_t_g173_wind_direction
w_t_g173_wind_direction_relative
w_t_g174_air_density
w_t_g174_temperature_ambient_merged
w_t_g174_real_power_a_c
w_t_g174_theoretical_power
w_t_g174_wind_speed
w_t_g174_temperature_ambient
w_t_g174_real_power_a_c_2
w_t_g174_nacelle_position
w_t_g174_blade_position_1
w_t_g174_blade_position_2
w_t_g174_blade_position_3
w_t_g174_blade_setpoint_position_1
w_t_g174_blade_setpoint_position_2
w_t_g174_blade_setpoint_position_3
w_t_g174_wind_speed_2
w_t_g174_wind_direction
w_t_g174_wind_direction_relative
w_t_g175_air_density
w_t_g175_temperature_ambient_merged
w_t_g175_real_power_a_c
w_t_g175_theoretical_power
w_t_g175_wind_speed
w_t_g175_temperature_ambient
w_t_g175_real_power_a_c_2
w_t_g175_nacelle_position
w_t_g175_blade_position_1
w_t_g175_blade_position_2
w_t_g175_blade_position_3
w_t_g175_blade_setpoint_position_1
w_t_g175_blade_setpoint_position_2
w_t_g175_blade_setpoint_position_3
w_t_g175_wind_speed_2
w_t_g175_wind_direction
w_t_g175_wind_direction_relative
w_t_g176_air_density
w_t_g176_temperature_ambient_merged
w_t_g176_real_power_a_c
w_t_g176_theoretical_power
w_t_g176_wind_speed
w_t_g176_temperature_ambient
w_t_g176_real_power_a_c_2
w_t_g176_nacelle_position
w_t_g176_blade_position_1
w_t_g176_blade_position_2
w_t_g176_blade_position_3
w_t_g176_blade_setpoint_position_1
w_t_g176_blade_setpoint_position_2
w_t_g176_blade_setpoint_position_3
w_t_g176_wind_speed_2
w_t_g176_wind_direction
w_t_g176_wind_direction_relative
w_t_g177_air_density
w_t_g177_temperature_ambient_merged
w_t_g177_real_power_a_c
w_t_g177_theoretical_power
w_t_g177_wind_speed
w_t_g177_temperature_ambient
w_t_g177_real_power_a_c_2
w_t_g177_nacelle_position
w_t_g177_blade_position_1
w_t_g177_blade_position_2
w_t_g177_blade_position_3
w_t_g177_blade_setpoint_position_1
w_t_g177_blade_setpoint_position_2
w_t_g177_blade_setpoint_position_3
w_t_g177_wind_speed_2
w_t_g177_wind_direction
w_t_g177_wind_direction_relative
w_t_g178_air_density
w_t_g178_temperature_ambient_merged
w_t_g178_real_power_a_c
w_t_g178_theoretical_power
w_t_g178_wind_speed
w_t_g178_temperature_ambient
w_t_g178_real_power_a_c_2
w_t_g178_nacelle_position
w_t_g178_blade_position_1
w_t_g178_blade_position_2
w_t_g178_blade_position_3
w_t_g178_blade_setpoint_position_1
w_t_g178_blade_setpoint_position_2
w_t_g178_blade_setpoint_position_3
w_t_g178_wind_speed_2
w_t_g178_wind_direction
w_t_g178_wind_direction_relative
w_t_g179_air_density
w_t_g179_temperature_ambient_merged
w_t_g179_real_power_a_c
w_t_g179_theoretical_power
w_t_g179_wind_speed
w_t_g179_temperature_ambient
w_t_g179_real_power_a_c_2
w_t_g179_nacelle_position
w_t_g179_blade_position_1
w_t_g179_blade_position_2
w_t_g179_blade_position_3
w_t_g179_blade_setpoint_position_1
w_t_g179_blade_setpoint_position_2
w_t_g179_blade_setpoint_position_3
w_t_g179_wind_speed_2
w_t_g179_wind_direction
w_t_g179_wind_direction_relative
w_t_g180_air_density
w_t_g180_temperature_ambient_merged
w_t_g180_real_power_a_c
w_t_g180_theoretical_power
w_t_g180_wind_speed
w_t_g180_temperature_ambient
w_t_g180_real_power_a_c_2
w_t_g180_nacelle_position
w_t_g180_blade_position_1
w_t_g180_blade_position_2
w_t_g180_blade_position_3
w_t_g180_blade_setpoint_position_1
w_t_g180_blade_setpoint_position_2
w_t_g180_blade_setpoint_position_3
w_t_g180_wind_speed_2
w_t_g180_wind_direction
w_t_g180_wind_direction_relative
w_t_g181_air_density
w_t_g181_temperature_ambient_merged
w_t_g181_real_power_a_c
w_t_g181_theoretical_power
w_t_g181_wind_speed
w_t_g181_temperature_ambient
w_t_g181_real_power_a_c_2
w_t_g181_nacelle_position
w_t_g181_blade_position_1
w_t_g181_blade_position_2
w_t_g181_blade_position_3
w_t_g181_blade_setpoint_position_1
w_t_g181_blade_setpoint_position_2
w_t_g181_blade_setpoint_position_3
w_t_g181_wind_speed_2
w_t_g181_wind_direction
w_t_g181_wind_direction_relative
w_t_g182_air_density
w_t_g182_temperature_ambient_merged
w_t_g182_real_power_a_c
w_t_g182_theoretical_power
w_t_g182_wind_speed
w_t_g182_temperature_ambient
w_t_g182_real_power_a_c_2
w_t_g182_nacelle_position
w_t_g182_blade_position_1
w_t_g182_blade_position_2
w_t_g182_blade_position_3
w_t_g182_blade_setpoint_position_1
w_t_g182_blade_setpoint_position_2
w_t_g182_blade_setpoint_position_3
w_t_g182_wind_speed_2
w_t_g182_wind_direction
w_t_g182_wind_direction_relative
w_t_g183_air_density
w_t_g183_temperature_ambient_merged
w_t_g183_real_power_a_c
w_t_g183_theoretical_power
w_t_g183_wind_speed
w_t_g183_temperature_ambient
w_t_g183_real_power_a_c_2
w_t_g183_nacelle_position
w_t_g183_blade_position_1
w_t_g183_blade_position_2
w_t_g183_blade_position_3
w_t_g183_blade_setpoint_position_1
w_t_g183_blade_setpoint_position_2
w_t_g183_blade_setpoint_position_3
w_t_g183_wind_speed_2
w_t_g183_wind_direction
w_t_g183_wind_direction_relative
w_t_g184_air_density
w_t_g184_temperature_ambient_merged
w_t_g184_real_power_a_c
w_t_g184_theoretical_power
w_t_g184_wind_speed
w_t_g184_temperature_ambient
w_t_g184_real_power_a_c_2
w_t_g184_nacelle_position
w_t_g184_blade_position_1
w_t_g184_blade_position_2
w_t_g184_blade_position_3
w_t_g184_blade_setpoint_position_1
w_t_g184_blade_setpoint_position_2
w_t_g184_blade_setpoint_position_3
w_t_g184_wind_speed_2
w_t_g184_wind_direction
w_t_g184_wind_direction_relative
w_t_g185_air_density
w_t_g185_temperature_ambient_merged
w_t_g185_real_power_a_c
w_t_g185_theoretical_power
w_t_g185_wind_speed
w_t_g185_temperature_ambient
w_t_g185_real_power_a_c_2
w_t_g185_nacelle_position
w_t_g185_blade_position_1
w_t_g185_blade_position_2
w_t_g185_blade_position_3
w_t_g185_blade_setpoint_position_1
w_t_g185_blade_setpoint_position_2
w_t_g185_blade_setpoint_position_3
w_t_g185_wind_speed_2
w_t_g185_wind_direction
w_t_g185_wind_direction_relative
w_t_g186_air_density
w_t_g186_temperature_ambient_merged
w_t_g186_real_power_a_c
w_t_g186_theoretical_power
w_t_g186_wind_speed
w_t_g186_temperature_ambient
w_t_g186_real_power_a_c_2
w_t_g186_nacelle_position
w_t_g186_blade_position_1
w_t_g186_blade_position_2
w_t_g186_blade_position_3
w_t_g186_blade_setpoint_position_1
w_t_g186_blade_setpoint_position_2
w_t_g186_blade_setpoint_position_3
w_t_g186_wind_speed_2
w_t_g186_wind_direction
w_t_g186_wind_direction_relative
w_t_g187_air_density
w_t_g187_temperature_ambient_merged
w_t_g187_real_power_a_c
w_t_g187_theoretical_power
w_t_g187_wind_speed
w_t_g187_temperature_ambient
w_t_g187_real_power_a_c_2
w_t_g187_nacelle_position
w_t_g187_blade_position_1
w_t_g187_blade_position_2
w_t_g187_blade_position_3
w_t_g187_blade_setpoint_position_1
w_t_g187_blade_setpoint_position_2
w_t_g187_blade_setpoint_position_3
w_t_g187_wind_speed_2
w_t_g187_wind_direction
w_t_g187_wind_direction_relative
w_t_g188_air_density
w_t_g188_temperature_ambient_merged
w_t_g188_real_power_a_c
w_t_g188_theoretical_power
w_t_g188_wind_speed
w_t_g188_temperature_ambient
w_t_g188_real_power_a_c_2
w_t_g188_nacelle_position
w_t_g188_blade_position_1
w_t_g188_blade_position_2
w_t_g188_blade_position_3
w_t_g188_blade_setpoint_position_1
w_t_g188_blade_setpoint_position_2
w_t_g188_blade_setpoint_position_3
w_t_g188_wind_speed_2
w_t_g188_wind_direction
w_t_g188_wind_direction_relative
w_t_g189_air_density
w_t_g189_temperature_ambient_merged
w_t_g189_real_power_a_c
w_t_g189_theoretical_power
w_t_g189_wind_speed
w_t_g189_temperature_ambient
w_t_g189_real_power_a_c_2
w_t_g189_nacelle_position
w_t_g189_blade_position_1
w_t_g189_blade_position_2
w_t_g189_blade_position_3
w_t_g189_blade_setpoint_position_1
w_t_g189_blade_setpoint_position_2
w_t_g189_blade_setpoint_position_3
w_t_g189_wind_speed_2
w_t_g189_wind_direction
w_t_g189_wind_direction_relative
w_t_g190_air_density
w_t_g190_temperature_ambient_merged
w_t_g190_real_power_a_c
w_t_g190_theoretical_power
w_t_g190_wind_speed
w_t_g190_temperature_ambient
w_t_g190_real_power_a_c_2
w_t_g190_nacelle_position
w_t_g190_blade_position_1
w_t_g190_blade_position_2
w_t_g190_blade_position_3
w_t_g190_blade_setpoint_position_1
w_t_g190_blade_setpoint_position_2
w_t_g190_blade_setpoint_position_3
w_t_g190_wind_speed_2
w_t_g190_wind_direction
w_t_g190_wind_direction_relative
w_t_g191_air_density
w_t_g191_temperature_ambient_merged
w_t_g191_real_power_a_c
w_t_g191_theoretical_power
w_t_g191_wind_speed
w_t_g191_temperature_ambient
w_t_g191_real_power_a_c_2
w_t_g191_nacelle_position
w_t_g191_blade_position_1
w_t_g191_blade_position_2
w_t_g191_blade_position_3
w_t_g191_blade_setpoint_position_1
w_t_g191_blade_setpoint_position_2
w_t_g191_blade_setpoint_position_3
w_t_g191_wind_speed_2
w_t_g191_wind_direction
w_t_g191_wind_direction_relative
w_t_g192_air_density
w_t_g192_temperature_ambient_merged
w_t_g192_real_power_a_c
w_t_g192_theoretical_power
w_t_g192_wind_speed
w_t_g192_temperature_ambient
w_t_g192_real_power_a_c_2
w_t_g192_nacelle_position
w_t_g192_blade_position_1
w_t_g192_blade_position_2
w_t_g192_blade_position_3
w_t_g192_blade_setpoint_position_1
w_t_g192_blade_setpoint_position_2
w_t_g192_blade_setpoint_position_3
w_t_g192_wind_speed_2
w_t_g192_wind_direction
w_t_g192_wind_direction_relative
w_t_g193_air_density
w_t_g193_temperature_ambient_merged
w_t_g193_real_power_a_c
w_t_g193_theoretical_power
w_t_g193_wind_speed
w_t_g193_temperature_ambient
w_t_g193_real_power_a_c_2
w_t_g193_nacelle_position

In [1]:
import pandas as pd
import re

# Load processed data
df = pd.read_parquet(
    "../../data/processed/alta10_turbine_data_cleaned.parquet"
)

# Use time as the index
df_turbines = df.set_index("utc_time")

new_columns = []

for col in df_turbines.columns:

    # Match columns like w_t_g150_wind_speed
    match = re.match(r"(w_t_g\d+)_(.+)", col)

    if match:
        turbine = match.group(1)
        variable = match.group(2)

        # Rename w_t_g150 -> wtg150
        turbine = turbine.replace("w_t_g", "wtg")

        new_columns.append((turbine, variable))

    else:
        new_columns.append(("other", col))

# Create grouped turbine / variable columns
df_turbines.columns = pd.MultiIndex.from_tuples(
    new_columns,
    names=["turbine", "variable"]
)

# Sort turbines together
df_turbines = df_turbines.sort_index(axis=1)

print(df_turbines.shape)

df_turbines.head()

(4464, 798)

turbine                  wtg150                                    \
variable            air_density blade_position_2 blade_position_3
utc_time
2026-01-01 08:00:00    1.092081        -1.056245        -0.643520
2026-01-01 08:10:00    0.800856        -1.077751        -0.680390
2026-01-01 08:20:00    1.089478        -0.445800        -0.039797
2026-01-01 08:30:00    0.800936        -1.205972        -0.786801
2026-01-01 08:40:00    1.090836        -1.205672        -0.786363

turbine                                                                  \
variable            blade_setpoint_position_1 blade_setpoint_position_2
utc_time
2026-01-01 08:00:00                  2.307242                 -0.892182
2026-01-01 08:10:00                  2.354385                 -0.845038
2026-01-01 08:20:00                  2.813232                 -0.386191
2026-01-01 08:30:00                       NaN                       NaN
2026-01-01 08:40:00                       NaN                       NaN

turbine                                                                        \
variable            blade_setpoint_position_3 nacelle_position real_power_a_c
utc_time
2026-01-01 08:00:00                 -0.471435       118.785714      672.60510
2026-01-01 08:10:00                 -0.424893       117.066667      541.30096
2026-01-01 08:20:00                  0.032674       118.812500      237.94884
2026-01-01 08:30:00                       NaN              NaN      503.22354
2026-01-01 08:40:00                       NaN       130.000000      444.42767

turbine                                                   ...  \
variable            real_power_a_c_2 temperature_ambient  ...
utc_time                                                  ...
2026-01-01 08:00:00       670.286714            8.299405  ...
2026-01-01 08:10:00       542.747853            8.573889  ...
2026-01-01 08:20:00       239.185173            8.972823  ...
2026-01-01 08:30:00       504.556470            8.531316  ...
2026-01-01 08:40:00       444.157211            8.621079  ...

turbine                       wtg197                                  \
variable            nacelle_position real_power_a_c real_power_a_c_2
utc_time
2026-01-01 08:00:00        62.500000      1232.1998      1229.936331
2026-01-01 08:10:00        59.000000       990.2687       990.641605
2026-01-01 08:20:00        58.666667      1074.2076      1074.568828
2026-01-01 08:30:00        67.333333      1108.8040      1108.957917
2026-01-01 08:40:00        67.100000      1124.4481      1123.277779

turbine                                                             \
variable            temperature_ambient temperature_ambient_merged
utc_time
2026-01-01 08:00:00            6.258348                   6.258348
2026-01-01 08:10:00            6.331188                   6.331188
2026-01-01 08:20:00            6.456590                   6.456590
2026-01-01 08:30:00            6.545990                   6.545990
2026-01-01 08:40:00            6.563307                   6.563307

turbine                                                                       \
variable            theoretical_power wind_direction wind_direction_relative
utc_time
2026-01-01 08:00:00         1418.4381      54.739130               -6.454545
2026-01-01 08:10:00          817.2081      52.763514               -5.510949
2026-01-01 08:20:00         1234.4576      53.654930               -4.808824
2026-01-01 08:30:00          843.8777      60.771812               -6.313869
2026-01-01 08:40:00         1250.2133      60.806897               -6.318519

turbine
variable            wind_speed wind_speed_2
utc_time
2026-01-01 08:00:00   8.669571     8.664497
2026-01-01 08:10:00   8.006839     8.000924
2026-01-01 08:20:00   8.203914     8.207936
2026-01-01 08:30:00   8.110932     8.099642
2026-01-01 08:40:00   8.245337     8.257563

[5 rows x 798 columns]

In [2]:
import os

# Create processed folder if needed
processed_dir = "../../data/processed"
os.makedirs(processed_dir, exist_ok=True)

# Save the grouped turbine dataframe
output_path = os.path.join(
    processed_dir,
    "alta10_turbine_data_grouped.parquet"
)

df_turbines.to_parquet(output_path)

print("Saved to:")
print(output_path)

print("\nShape:")
print(df_turbines.shape)

Saved to:
../../data/processed\alta10_turbine_data_grouped.parquet

Shape:
(4464, 798)